import Link from 'next/link'

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: `By accessing or using METARDU ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, you must not use the Platform. These Terms constitute a legally binding agreement between you ("User", "you", or "your") and METARDU ("we", "us", or "our"). We may update these Terms from time to time as described in Section 18. Your continued use of the Platform after any changes constitutes acceptance of the revised Terms. If you are using the Platform on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.`,
  },
  {
    title: '2. Description of Service',
    body: `METARDU provides survey computation, field data collection, cadastral mapping, project management, and statutory document generation tools designed for professional land surveyors operating in Kenya and East Africa. The Platform supports coordinate geometry calculations, traverse adjustments, deed plan generation, mutation form preparation, submission package assembly, and related survey workflows. The Platform uses the Arc 1960 / UTM Zone 37S coordinate reference system (EPSG:21037) and computes in accordance with the Survey Act Cap 299, the Survey Regulations 1994, and the RDM 1.1 accuracy standards as published by the Survey of Kenya. The Platform may be accessed via web browser or mobile application, and certain features may be available offline subject to device capabilities and synchronization requirements.`,
  },
  {
    title: '3. Professional Responsibility and Disclaimer',
    body: `METARDU IS A COMPUTATION TOOL, NOT A SUBSTITUTE FOR PROFESSIONAL SURVEYOR JUDGMENT. All calculations, coordinates, areas, bearings, distances, deed plans, mutation forms, computation sheets, certificates, schedules, and reports generated by the Platform are computational outputs that MUST be independently verified by a licensed land surveyor registered with the Institution of Surveyors of Kenya (ISK) or the Ethics and Anti-Corruption Commission Land Surveyors Board before being relied upon for any legal, construction, registration, or boundary determination purpose. METARDU does not certify, authenticate, or guarantee the accuracy, completeness, or fitness for purpose of any computational output. The Platform performs mathematical operations on data you provide; errors in input data, projection parameters, or adjustment assumptions will produce erroneous outputs. Users are solely responsible for validating all outputs against field observations, control surveys, and applicable regulatory standards. No output from this Platform constitutes a certified survey, a registered deed plan, or an authenticated document under the Survey Act Cap 299 unless separately certified by a licensed surveyor and authenticated by the Survey of Kenya.`,
  },
  {
    title: '4. User Accounts and Registration',
    body: `To access certain features of the Platform, you must register an account. You agree to provide accurate, current, and complete information during registration and to update such information as necessary. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us at security@metardu.app of any unauthorized use of your account. We reserve the right to suspend or terminate accounts that provide false registration information, including false ISK or EBK registration numbers. Surveyor verification status on the Platform does not constitute endorsement or certification by METARDU of a user's professional qualifications. Each user must maintain a single account; sharing accounts between individuals is prohibited. You must be at least 18 years of age to create an account.`,
  },
  {
    title: '5. User Content and Data Ownership',
    body: `You retain full ownership of all survey coordinates, field observations, project data, uploaded files, photographs, notes, computed results, and generated documents that you create or upload to the Platform ("User Content"). By using the Platform, you grant METARDU a limited, non-exclusive, non-transferable license to process, store, and display your User Content solely for the purpose of providing the Platform services to you. We do not claim any ownership interest in your User Content. You represent and warrant that you have all necessary rights, permissions, and consents to process and store any personal, land, client, or field data entered into the Platform, including compliance with the Kenya Data Protection Act, 2019 where applicable. You are solely responsible for ensuring that your use of the Platform complies with the Survey Act Cap 299, the Land Registration Act 2012, and any other applicable laws regarding survey data handling and client confidentiality. METARDU will not access, review, or modify your User Content except as necessary to provide the service, comply with legal obligations, or investigate suspected violations of these Terms.`,
  },
  {
    title: '6. Acceptable Use',
    body: `You agree not to: (a) use the Platform for any unlawful purpose or in violation of any applicable law or regulation; (b) attempt to gain unauthorized access to any part of the Platform, other users' accounts, or any systems or networks connected to the Platform; (c) use the Platform to produce fraudulent, misleading, or falsified survey documents; (d) reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the Platform; (e) use automated scripts, bots, or scraping tools to access the Platform without our written consent; (f) interfere with or disrupt the Platform's servers, networks, or other users' use of the Platform; (g) upload content that contains viruses, malware, or other harmful code; (h) use the Platform to process survey data for jurisdictions or purposes not supported by the Platform's coordinate reference systems and computation standards without independent verification; (i) impersonate any person or entity, including falsely representing ISK or EBK registration status. We reserve the right to investigate and take appropriate action against anyone who, in our sole discretion, violates this provision.`,
  },
  {
    title: '7. Subscriptions and Payments',
    body: `Certain features of the Platform require a paid subscription or one-time payment. Subscription plans, pricing, and feature availability are described on our pricing page and may be updated from time to time with 30 days' prior notice. All prices are listed in the applicable currency and exclude applicable taxes unless stated otherwise. Payments may be processed through Stripe, PayPal, or M-Pesa (Safaricom Daraja API) as selected by you at the time of payment. By providing payment information, you represent and warrant that you are authorized to use the designated payment method. Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date. We reserve the right to change our pricing upon 30 days' prior notice; such changes will take effect at the start of the next billing period. For refund and cancellation policies, please refer to our Refund Policy at /docs/refund.`,
  },
  {
    title: '8. Limitation of Liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY KENYAN LAW: (a) METARDU SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE PLATFORM; (b) METARDU'S TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE PLATFORM SHALL NOT EXCEED THE TOTAL AMOUNT YOU PAID TO METARDU IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM; (c) METARDU SHALL NOT BE LIABLE FOR ANY ERRORS, INACCURACIES, OR OMISSIONS IN COMPUTATIONAL OUTPUTS, INCLUDING BUT NOT LIMITED TO COORDINATE CALCULATIONS, AREA COMPUTATIONS, BEARING AND DISTANCE DERIVATIONS, TRAVERSE ADJUSTMENTS, OR DOCUMENT GENERATION, AS THE PLATFORM IS A COMPUTATIONAL TOOL SUBJECT TO THE PROFESSIONAL VERIFICATION REQUIREMENTS DESCRIBED IN SECTION 3; (d) METARDU SHALL NOT BE LIABLE FOR ANY LOSS, DAMAGE, OR LIABILITY ARISING FROM A USER'S RELIANCE ON UNVERIFIED COMPUTATIONAL OUTPUTS, INCLUDING BUT NOT LIMITED TO CONSTRUCTION ERRORS, BOUNDARY DISPUTES, REGISTRATION FAILURES, OR PROFESSIONAL NEGLIGENCE CLAIMS; (e) METARDU SHALL NOT BE LIABLE FOR ANY UNAUTHORIZED ACCESS TO YOUR DATA RESULTING FROM YOUR FAILURE TO MAINTAIN THE CONFIDENTIALITY OF YOUR ACCOUNT CREDENTIALS. THE LIMITATIONS IN THIS SECTION APPLY REGARDLESS OF THE LEGAL THEORY ON WHICH THE CLAIM IS BASED, WHETHER CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE.`,
  },
  {
    title: '9. Indemnification',
    body: `You agree to indemnify, defend, and hold harmless METARDU, its officers, directors, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising from or related to: (a) your use of or inability to use the Platform; (b) your violation of these Terms; (c) your violation of any applicable law, regulation, or third-party right, including the Survey Act Cap 299, the Kenya Data Protection Act 2019, or intellectual property rights; (d) any User Content you submit, upload, or create on the Platform; (e) any survey outputs, documents, or deliverables you produce using the Platform that are later found to contain errors, inaccuracies, or misrepresentations; (f) any claim by a third party that survey work performed using the Platform caused financial loss, property damage, construction error, boundary dispute, or other harm. This indemnification obligation will survive the termination of your account and these Terms.`,
  },
  {
    title: '10. Warranty Disclaimer',
    body: `THE PLATFORM IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. TO THE FULLEST EXTENT PERMITTED BY KENYAN LAW, METARDU DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO: (a) IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT; (b) WARRANTIES THAT THE PLATFORM WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (c) WARRANTIES THAT COMPUTATIONAL RESULTS WILL BE ACCURATE, COMPLETE, OR SUITABLE FOR ANY PARTICULAR SURVEY, REGISTRATION, OR LEGAL PURPOSE; (d) WARRANTIES THAT THE PLATFORM MEETS THE REQUIREMENTS OF THE SURVEY ACT CAP 299, THE SURVEY REGULATIONS 1994, OR ANY OTHER REGULATORY STANDARD. YOU ACKNOWLEDGE THAT THE PLATFORM IS A COMPUTATIONAL TOOL AND THAT ALL OUTPUTS REQUIRE INDEPENDENT PROFESSIONAL VERIFICATION AS DESCRIBED IN SECTION 3. NO ADVICE OR INFORMATION OBTAINED FROM METARDU OR THROUGH THE PLATFORM SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.`,
  },
  {
    title: '11. Intellectual Property',
    body: `The Platform, including its software, design, text, graphics, logos, and the selection and arrangement thereof, is owned by METARDU and is protected by Kenyan and international intellectual property laws. The METARDU name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of METARDU. You may not use such marks without our prior written permission. Your User Content remains your property as described in Section 5. We reserve all rights not expressly granted in these Terms.`,
  },
  {
    title: '12. Account Termination',
    body: `You may terminate your account at any time by contacting support@metardu.app. Upon termination: (a) your subscription will not be renewed for the next billing period; (b) you will retain access until the end of the current paid period; (c) after the paid period ends, your account and User Content may be deleted in accordance with our data retention policies described in our Data Protection Policy; (d) we are not liable for any loss of data upon account termination. We reserve the right to suspend or terminate your account immediately, without prior notice, for: (i) violation of these Terms; (ii) conduct that we reasonably believe may cause harm to METARDU, other users, or third parties; (iii) provision of false registration information, including false professional credentials; (iv) use of the Platform to produce fraudulent or falsified survey documents; (v) prolonged inactivity exceeding 12 months for free accounts. Upon such termination, you must cease all use of the Platform.`,
  },
  {
    title: '13. Mobile and Offline Workflows',
    body: `Certain Platform features are available on mobile devices and may support offline operation. These features depend on device permissions, network quality, browser support, storage availability, GPS accuracy, and battery life. METARDU does not guarantee the availability, accuracy, or reliability of mobile or offline features. Data captured offline will be synchronized when connectivity is restored, but we are not responsible for data loss resulting from device failure, storage limitations, or synchronization errors. Desktop use is recommended for final review, official drawings, large tables, ZIP packages, and statutory submissions. Mobile GPS accuracy is not sufficient for cadastral survey purposes and should not be relied upon for boundary determination.`,
  },
  {
    title: '14. Service Availability',
    body: `We work to keep METARDU reliable and available, but the service may experience interruptions due to scheduled maintenance, network disruptions, dependency failures, security incidents, force majeure events, or other causes beyond our control. We do not guarantee uninterrupted access to the Platform. We will make reasonable efforts to provide advance notice of scheduled maintenance. In the event of a significant outage, we will post updates through our normal communication channels. We are not liable for any loss or damage resulting from Platform unavailability.`,
  },
  {
    title: '15. Third-Party Services',
    body: `The Platform integrates with third-party services, including but not limited to: payment processors (Stripe, PayPal, M-Pesa), mapping tile providers (OpenStreetMap, Esri, CartoDB), cloud storage providers, error monitoring services (Sentry), and AI computation services. Your use of these third-party services is subject to their respective terms and privacy policies. METARDU is not responsible for the availability, accuracy, or practices of any third-party service. Any disputes with third-party providers are solely between you and that provider. Changes to third-party services beyond our control may affect Platform functionality.`,
  },
  {
    title: '16. Governing Law and Dispute Resolution',
    body: `These Terms are governed by and construed in accordance with the laws of the Republic of Kenya, without regard to its conflict of law principles. Any dispute arising from or related to these Terms or the Platform shall first be attempted to be resolved through good-faith negotiation between the parties. If negotiation is unsuccessful within 30 days, the dispute shall be referred to mediation administered by the Nairobi Centre for International Arbitration (NCIA) in accordance with its rules. If mediation fails, the dispute shall be finally resolved by arbitration administered by the NCIA in Nairobi, Kenya, in accordance with its Arbitration Rules. The arbitral tribunal shall consist of one arbitrator appointed in accordance with the NCIA rules. The language of the arbitration shall be English. The seat of arbitration shall be Nairobi, Kenya. Notwithstanding the foregoing, either party may seek injunctive or equitable relief in any court of competent jurisdiction in Kenya for matters involving intellectual property infringement, unauthorized access, or breach of confidentiality.`,
  },
  {
    title: '17. Severability and Waiver',
    body: `If any provision of these Terms is held to be unenforceable or invalid by a court of competent jurisdiction, such provision will be changed and interpreted to accomplish its objectives to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect. The failure of METARDU to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. Any waiver of any provision of these Terms will be effective only if in writing and signed by METARDU.`,
  },
  {
    title: '18. Modifications to Terms',
    body: `We reserve the right to modify these Terms at any time. We will provide notice of material changes by: (a) posting the updated Terms on the Platform with a revised "Effective date"; (b) sending an email notification to the address associated with your account; or (c) displaying a prominent notice within the Platform. Material changes will take effect 30 days after such notice. Non-material changes (such as grammatical corrections or formatting) take effect immediately upon posting. Your continued use of the Platform after the effective date of any changes constitutes your acceptance of the revised Terms. If you do not agree to the revised Terms, you must discontinue use of the Platform and terminate your account.`,
  },
  {
    title: '19. Entire Agreement',
    body: `These Terms, together with our Privacy Policy, Data Protection Policy, Cookie Policy, and Refund Policy, constitute the entire agreement between you and METARDU regarding your use of the Platform, and supersede any prior agreements or understandings, whether written or oral, regarding the subject matter hereof. No term or condition of these Terms may be varied or amended except as provided in Section 18. For the avoidance of doubt, any terms or conditions proposed by you that are in addition to or conflict with these Terms are hereby rejected and shall not form part of any agreement between us.`,
  },
  {
    title: '20. Contact',
    body: `For questions about these Terms, your account, or our services, please contact us at: METARDU Legal, support@metardu.app. For data protection inquiries, contact our Data Protection Officer at dpo@metardu.app. For billing inquiries, contact billing@metardu.app. All formal legal notices should be sent to: METARDU Legal, P.O. Box Nairobi, Kenya.`,
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen py-16">
      <div className="mx-auto max-w-4xl px-6">
        <Link href="/docs" className="mb-8 inline-block text-[var(--accent)] hover:underline">
          Back to Documentation
        </Link>

        <p className="mb-3 text-sm uppercase tracking-[0.2em] text-[var(--text-muted)]">Legal</p>
        <h1 className="mb-4 text-4xl font-bold text-[var(--text-primary)]">Terms of Service</h1>
        <p className="mb-10 text-[var(--text-secondary)]">Effective date: May 22, 2026</p>

        <div className="space-y-6">
          {sections.map((section) => (
            <section key={section.title} className="rounded-lg border border-[var(--border-color)] bg-[var(--bg-secondary)] p-6">
              <h2 className="mb-3 text-xl font-semibold text-[var(--text-primary)]">{section.title}</h2>
              <p className="leading-7 text-[var(--text-secondary)]">{section.body}</p>
            </section>
          ))}
        </div>

        <div className="mt-10 rounded-lg border border-[var(--border-color)] bg-[var(--bg-secondary)] p-6">
          <h2 className="mb-3 text-xl font-semibold text-[var(--text-primary)]">Related Policies</h2>
          <ul className="space-y-2 text-[var(--text-secondary)]">
            <li><Link href="/docs/privacy" className="text-[var(--accent)] hover:underline">Privacy Policy</Link></li>
            <li><Link href="/docs/data-protection" className="text-[var(--accent)] hover:underline">Data Protection Policy</Link></li>
            <li><Link href="/docs/refund" className="text-[var(--accent)] hover:underline">Refund Policy</Link></li>
            <li><Link href="/docs/cookies" className="text-[var(--accent)] hover:underline">Cookie Policy</Link></li>
          </ul>
        </div>
      </div>
    </div>
  )
}
