'use client'

import { useState } from 'react'
import { Download, FileText, Map, Copy, Check, Loader2 } from 'lucide-react'

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface ExportPoint {
  name: string
  easting: number
  northing: number
  elevation?: number
}

interface ExportLeg {
  from: string
  to: string
  bearing: number
  distance: number
}

interface DrawingExportToolbarProps {
  projectName: string
  points: ExportPoint[]
  legs?: ExportLeg[]
  className?: string
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function safeFileName(name: string, ext: string) {
  const date = new Date().toISOString().split('T')[0]
  return `${name.replace(/\s+/g, '_')}_${date}.${ext}`
}

/* ------------------------------------------------------------------ */
/*  Export handlers                                                    */
/* ------------------------------------------------------------------ */

async function exportDXF(
  projectName: string,
  points: ExportPoint[],
  legs?: ExportLeg[],
): Promise<void> {
  const resp = await fetch('/api/compute/export/dxf', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      projectName,
      points: points.map(p => ({
        name: p.name,
        easting: p.easting,
        northing: p.northing,
        elevation: p.elevation ?? undefined,
        is_control: false,
      })),
      traverseLegs: (legs ?? []).map(l => ({
        from: l.from,
        to: l.to,
        distance: l.distance,
        bearing: l.bearing,
      })),
    }),
  })
  const data = await resp.json()
  if (!resp.ok) throw new Error(data.error || 'DXF export failed')
  const blob = new Blob([data.dxf], { type: 'application/dxf' })
  triggerDownload(blob, data.filename || safeFileName(projectName, 'dxf'))
}

function exportGeoJSON(
  projectName: string,
  points: ExportPoint[],
): void {
  const coords = points.map(p => [p.easting, p.northing] as [number, number])
  const isClosed = coords.length > 2
  if (isClosed) {
    coords.push(coords[0]) // close the polygon
  }

  const geojson = {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: { name: projectName },
        geometry: {
          type: isClosed ? 'Polygon' : 'LineString',
          coordinates: isClosed ? [coords] : coords,
        },
      },
    ],
  }

  const blob = new Blob([JSON.stringify(geojson, null, 2)], {
    type: 'application/geo+json',
  })
  triggerDownload(blob, safeFileName(projectName, 'geojson'))
}

async function exportPDF(
  projectName: string,
  points: ExportPoint[],
): Promise<void> {
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')

  const doc = new jsPDF({ orientation: 'landscape' })

  doc.setFontSize(16)
  doc.text(projectName, 14, 18)

  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text(`Generated by METARDU  •  ${new Date().toLocaleString()}`, 14, 25)

  const head = [['#', 'Station', 'Easting (m)', 'Northing (m)', 'Elevation (m)']] as any
  const body = points.map((p, i) => [
    i + 1,
    p.name,
    p.easting.toFixed(4),
    p.northing.toFixed(4),
    p.elevation != null ? p.elevation.toFixed(4) : '—',
  ])

  autoTable(doc, {
    startY: 30,
    head,
    body,
    theme: 'grid',
    styles: { fontSize: 9 },
    headStyles: { fillColor: [34, 34, 34] },
  })

  doc.save(safeFileName(projectName, 'pdf'))
}

async function copyCoordinates(points: ExportPoint[]): Promise<void> {
  const header = 'Station\tEasting\tNorthing'
  const rows = points.map(
    p => `${p.name}\t${p.easting.toFixed(4)}\t${p.northing.toFixed(4)}`,
  )
  const text = [header, ...rows].join('\n')

  try {
    await navigator.clipboard.writeText(text)
  } catch {
    const ta = document.createElement('textarea')
    ta.value = text
    document.body.appendChild(ta)
    ta.select()
    document.execCommand('copy')
    document.body.removeChild(ta)
  }
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export default function DrawingExportToolbar({
  projectName,
  points,
  legs,
  className = '',
}: DrawingExportToolbarProps) {
  const [loading, setLoading] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  async function handleDXF() {
    setLoading('dxf')
    try {
      await exportDXF(projectName, points, legs)
    } catch (err: any) {
      console.error('DXF export failed:', err)
    } finally {
      setLoading(null)
    }
  }

  function handleGeoJSON() {
    setLoading('geojson')
    try {
      exportGeoJSON(projectName, points)
    } catch (err: any) {
      console.error('GeoJSON export failed:', err)
    } finally {
      setLoading(null)
    }
  }

  async function handlePDF() {
    setLoading('pdf')
    try {
      await exportPDF(projectName, points)
    } catch (err: any) {
      console.error('PDF export failed:', err)
    } finally {
      setLoading(null)
    }
  }

  async function handleCopy() {
    setLoading('copy')
    try {
      await copyCoordinates(points)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err: any) {
      console.error('Copy failed:', err)
    } finally {
      setLoading(null)
    }
  }

  const btnBase =
    'inline-flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed'

  return (
    <div className={`flex flex-wrap items-center gap-2 ${className}`}>
      {/* DXF */}
      <button
        onClick={handleDXF}
        disabled={loading !== null || points.length === 0}
        className={`${btnBase} bg-blue-700 hover:bg-blue-600 text-white`}
        title="Export DXF"
      >
        {loading === 'dxf' ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : (
          <FileText className="w-3.5 h-3.5" />
        )}
        DXF
      </button>

      {/* GeoJSON */}
      <button
        onClick={handleGeoJSON}
        disabled={loading !== null || points.length === 0}
        className={`${btnBase} bg-emerald-700 hover:bg-emerald-600 text-white`}
        title="Export GeoJSON"
      >
        {loading === 'geojson' ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : (
          <Map className="w-3.5 h-3.5" />
        )}
        GeoJSON
      </button>

      {/* PDF */}
      <button
        onClick={handlePDF}
        disabled={loading !== null || points.length === 0}
        className={`${btnBase} bg-rose-700 hover:bg-rose-600 text-white`}
        title="Export PDF"
      >
        {loading === 'pdf' ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : (
          <Download className="w-3.5 h-3.5" />
        )}
        PDF
      </button>

      {/* Copy Coordinates */}
      <button
        onClick={handleCopy}
        disabled={loading !== null || points.length === 0}
        className={`${btnBase} bg-[var(--bg-tertiary)] hover:bg-[var(--border-hover)] text-[var(--text-primary)] border border-[var(--border-color)]`}
        title="Copy coordinates to clipboard"
      >
        {copied ? (
          <Check className="w-3.5 h-3.5 text-emerald-400" />
        ) : loading === 'copy' ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : (
          <Copy className="w-3.5 h-3.5" />
        )}
        {copied ? 'Copied!' : 'Copy'}
      </button>
    </div>
  )
}

export type { ExportPoint, ExportLeg, DrawingExportToolbarProps }
