import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { bearingToString, decimalToDMS } from '@/lib/engine/angles'
import { computeTraverseAccuracy, getAccuracyBadgeLabel } from '@/lib/reports/traverseAccuracy'
import { formatBearingDegMinSec } from '@/lib/reports/surveyPlan/geometry'
import type {
  SurveyReportData,
  SurveyReportOptions,
  ReportPoint,
  TraverseResult,
  ParcelData,
  BeaconDescription,
  SpotLevel,
  Photo,
  MobilisationData,
} from './types'

const AMBER: [number, number, number] = [232, 132, 26]
const DARK: [number, number, number] = [15, 15, 20]
const WHITE: [number, number, number] = [255, 255, 255]
const GRAY: [number, number, number] = [120, 120, 120]
const LIGHT_GRAY: [number, number, number] = [240, 240, 240]

let _yPos = 20
let _currentPage = 1

function reset() {
  _yPos = 20
  _currentPage = 1
}

function newPage(doc: jsPDF, minY = 260): void {
  if (_yPos > minY) {
    addPageFooter(doc)
    doc.addPage()
    _currentPage++
    _yPos = 20
  }
}

function checkPage(doc: jsPDF): void {
  if (_yPos > 260) {
    addPageFooter(doc)
    doc.addPage()
    _currentPage++
    _yPos = 20
  }
}

function addPageFooter(doc: jsPDF, opts?: { submission_number?: string }): void {
  doc.setFillColor(...DARK)
  doc.rect(0, 283, 210, 14, 'F')
  doc.setTextColor(...GRAY)
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by METARDU — Professional Surveying Platform', 15, 290)
  if (opts?.submission_number) {
    doc.text(opts.submission_number, 105, 290, { align: 'center' })
  }
  doc.text(`Page ${_currentPage}`, 195, 290, { align: 'right' })
}

function sectionTitle(doc: jsPDF, text: string, number?: string): void {
  checkPage(doc)
  doc.setTextColor(...AMBER)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  if (number) {
    doc.text(`${number}. ${text}`, 15, _yPos)
  } else {
    doc.text(text, 15, _yPos)
  }
  _yPos += 4
  doc.setDrawColor(...AMBER)
  doc.setLineWidth(0.5)
  doc.line(15, _yPos, 195, _yPos)
  _yPos += 5
}

function bodyText(doc: jsPDF, text: string, maxWidth = 180): void {
  checkPage(doc)
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const lines = doc.splitTextToSize(text, maxWidth)
  doc.text(lines, 15, _yPos)
  _yPos += lines.length * 4.5 + 3
}

function labelValue(doc: jsPDF, label: string, value: string, indent = 15): void {
  checkPage(doc)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...AMBER)
  doc.text(label, indent, _yPos)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(30, 30, 30)
  doc.text(value || '—', indent + 38, _yPos)
  _yPos += 5
}

function coverPage(doc: jsPDF, data: SurveyReportData, opts: SurveyReportOptions): void {
  doc.setFillColor(...DARK)
  doc.rect(0, 0, 210, 50, 'F')
  doc.setTextColor(...AMBER)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('METARDU', 15, 22)
  doc.setTextColor(...WHITE)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Professional Surveying Platform', 15, 32)
  doc.setFontSize(8)
  doc.setTextColor(...GRAY)
  doc.text(`Report Generated: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`, 15, 40)

  _yPos = 65

  const title = opts.reportTitle || 'Topographic / Boundary Survey Report'
  doc.setTextColor(...DARK)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(title.toUpperCase(), 15, _yPos)
  _yPos += 10

  doc.setFontSize(13)
  doc.setFont('helvetica', 'normal')
  doc.text(data.project.name, 15, _yPos)
  _yPos += 12

  doc.setDrawColor(...AMBER)
  doc.setLineWidth(1)
  doc.line(15, _yPos, 195, _yPos)
  _yPos += 8

  doc.setFontSize(9)
  doc.setTextColor(60, 60, 60)
  const rows: [string, string][] = [
    ['Location', data.project.location],
    ['Client', data.project.client_name || '—'],
    ['Survey Date', data.project.survey_date || new Date().toLocaleDateString('en-GB')],
    ['Datum', `${data.project.datum || 'ARC1960'} / UTM Zone ${data.project.utm_zone}${data.project.hemisphere || 'S'}`],
    ['Scale', `1:${(opts.scale || data.project.scale || 1000).toLocaleString()}`],
    ['Survey Type', data.project.survey_type || 'Cadastral / Boundary'],
    ['Parcel Ref.', opts.parcelRef || data.project.parcel_ref || '—'],
  ]
  for (const [l, v] of rows) {
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...AMBER)
    doc.text(`${l}:`, 15, _yPos)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(30, 30, 30)
    doc.text(v, 55, _yPos)
    _yPos += 6
  }

  _yPos += 6
  doc.setDrawColor(...AMBER)
  doc.setLineWidth(1)
  doc.line(15, _yPos, 195, _yPos)
  _yPos += 8

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...DARK)
  doc.text('SURVEYOR DETAILS', 15, _yPos)
  _yPos += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(30, 30, 30)
  const sRows: [string, string][] = [
    ['Name / Firm', data.project.surveyor_name || data.project.firm_name || '—'],
    ['LSK Licence', data.project.surveyor_licence || '—'],
    ['Address', data.project.firm_address || '—'],
    ['Phone', data.project.firm_phone || '—'],
    ['Email', data.project.firm_email || '—'],
  ]
  for (const [l, v] of sRows) {
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...AMBER)
    doc.text(`${l}:`, 15, _yPos)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(30, 30, 30)
    doc.text(v, 55, _yPos)
    _yPos += 6
  }
}

function tableOfContents(doc: jsPDF, data: SurveyReportData): void {
  doc.addPage()
  _currentPage++
  _yPos = 20

  doc.setTextColor(...AMBER)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('TABLE OF CONTENTS', 15, _yPos)
  _yPos += 8
  doc.setDrawColor(...AMBER)
  doc.setLineWidth(0.5)
  doc.line(15, _yPos, 195, _yPos)
  _yPos += 8

  const sections = [
    'Introduction & Scope',
    'Survey Methodology',
    'Control Network',
    'Traverse Computation',
    'Boundary Description',
    'Beacon Description',
    'Topographic Features',
    'Calculation Methodology',
    "Surveyor's Declaration",
    'Appendices',
  ]
  if (data.mobilisation) sections.splice(9, 0, 'Mobilisation Report')
  if (data.photos?.length) sections.splice(10, 0, 'Field Photographs')

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  sections.forEach((s, i) => {
    doc.setTextColor(30, 30, 30)
    doc.text(`${i + 1}. ${s}`, 15, _yPos)
    _yPos += 7
  })
}

function introductionSection(doc: jsPDF, data: SurveyReportData, opts: SurveyReportOptions): void {
  sectionTitle(doc, 'Introduction & Scope', '1')

  const defaultIntro = `This report documents the ${data.project.survey_type || 'boundary'} survey carried out at ${data.project.location}${data.project.municipality ? `, ${data.project.municipality}` : ''}. The survey was conducted to establish the boundaries and prepare a ${data.project.survey_type || 'cadastral'} plan for submission to the relevant authorities.`
  bodyText(doc, opts.customIntroduction || defaultIntro)

  _yPos += 2
  bodyText(doc, 'Standards applied: Survey conducted in accordance with the Survey Act Cap. 299, RDM 1.1 and the Geodetic Reference System for Kenya (GRS80 / ARC1960). Coordinates are referenced to UTM Zone 37S (EPSG:21037).')

  if (data.parcel) {
    const areaHa = data.parcel.area_ha.toFixed(4)
    const areaAcres = data.parcel.area_acres.toFixed(4)
    bodyText(doc, `The surveyed parcel has an area of ${data.parcel.area_sqm.toFixed(4)} m² (${areaHa} ha / ${areaAcres} acres) with a perimeter of ${data.parcel.perimeter_m.toFixed(2)} m.`)
  }
}

function methodologySection(doc: jsPDF, data: SurveyReportData): void {
  sectionTitle(doc, 'Survey Methodology', '2')
  bodyText(doc, 'Field observations were carried out using a total station or GNSS receiver. Traverse computation was performed using the Bowditch Rule for closed traverses. All computations were reduced to ARC1960 / UTM Zone 37S (EPSG:21037) as required by the Survey of Kenya.')
  _yPos += 2
  labelValue(doc, 'Coordinate System', `ARC1960 / UTM Zone ${data.project.utm_zone}${data.project.hemisphere || 'S'} (EPSG:21037)`)
  labelValue(doc, 'Reduction Method', data.traverse ? 'Bowditch Rule' : 'Coordinate Computation')
  labelValue(doc, 'Area Method', 'Coordinate (Shoelace Formula)')
  labelValue(doc, 'Scale', `1:${(data.project.scale || 1000).toLocaleString()}`)
}

function controlNetworkSection(doc: jsPDF, data: SurveyReportData): void {
  sectionTitle(doc, 'Control Network', '3')

  const controlPts = data.controlPoints.filter((p: any) => p.is_control)
  if (controlPts.length === 0) {
    bodyText(doc, 'No control points recorded for this survey.')
    return
  }

  autoTable(doc, {
    startY: _yPos,
    head: [['Point', 'Easting (m)', 'Northing (m)', 'Elevation (m)', 'Type', 'Order']],
    body: controlPts.map((p: any) => [
      p.name,
      p.easting.toFixed(4),
      p.northing.toFixed(4),
      p.elevation != null ? p.elevation.toFixed(3) : '—',
      p.monumentType || 'Control',
      p.control_order || '—',
    ]),
    headStyles: { fillColor: DARK, textColor: AMBER, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: LIGHT_GRAY },
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
    margin: { left: 15, right: 15 },
  })
  _yPos = (doc as any).lastAutoTable.finalY + 8

  if (data.traverse) {
    const acc = computeTraverseAccuracy(data.traverse.linearError, data.traverse.totalDistance)
    if (acc) {
      doc.setFillColor(LIGHT_GRAY[0], LIGHT_GRAY[1], LIGHT_GRAY[2])
      doc.rect(15, _yPos, 180, 20, 'F')
      doc.setDrawColor(...AMBER)
      doc.rect(15, _yPos, 180, 20, 'S')
      doc.setFontSize(8)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...AMBER)
      doc.text('Traverse Accuracy:', 20, _yPos + 7)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(30, 30, 30)
      doc.text(`${acc.order} — ${acc.formula}`, 20, _yPos + 13)
      _yPos += 24
    }
  }
}

function traverseComputationSection(doc: jsPDF, data: SurveyReportData): void {
  if (!data.traverse) return
  sectionTitle(doc, 'Traverse Computation', '4')
  const t = data.traverse

  newPage(doc)

  autoTable(doc, {
    startY: _yPos,
    head: [['Line', 'Dist (m)', 'Bearing', 'ΔN Raw', 'ΔE Raw', 'Adj ΔN', 'Adj ΔE']],
    body: t.legs.map((l: any) => [
      `${l.fromName} → ${l.toName}`,
      l.distance.toFixed(3),
      bearingToString(l.adjustedBearing || l.rawBearing),
      l.adjustedDeltaN.toFixed(4),
      l.adjustedDeltaE.toFixed(4),
      l.adjustedDeltaN.toFixed(4),
      l.adjustedDeltaE.toFixed(4),
    ]),
    headStyles: { fillColor: DARK, textColor: AMBER, fontStyle: 'bold', fontSize: 7 },
    bodyStyles: { fontSize: 7, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: LIGHT_GRAY },
    columnStyles: {
      0: { fontStyle: 'bold' },
      1: { halign: 'right' }, 2: { halign: 'center' },
      3: { halign: 'right' }, 4: { halign: 'right' },
      5: { halign: 'right' }, 6: { halign: 'right' },
    },
    margin: { left: 15, right: 15 },
  })
  _yPos = (doc as any).lastAutoTable.finalY + 8

  doc.setFillColor(LIGHT_GRAY[0], LIGHT_GRAY[1], LIGHT_GRAY[2])
  doc.rect(15, _yPos, 180, 38, 'F')
  doc.setDrawColor(...AMBER)
  doc.rect(15, _yPos, 180, 38, 'S')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(30, 30, 30)
  doc.text(`Total Distance: ${t.totalDistance.toFixed(3)} m`, 20, _yPos + 7)
  doc.text(`Closing Error E: ${t.closingErrorE.toFixed(4)} m`, 20, _yPos + 14)
  doc.text(`Closing Error N: ${t.closingErrorN.toFixed(4)} m`, 20, _yPos + 21)
  doc.text(`Linear Misclosure: ${t.linearError.toFixed(4)} m`, 20, _yPos + 28)

  const ratio = t.precisionRatio > 0 ? Math.round(1 / t.precisionRatio) : 0
  const acc = computeTraverseAccuracy(t.linearError, t.totalDistance)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...AMBER)
  doc.text(`Precision: 1 : ${ratio.toLocaleString()}`, 110, _yPos + 14)
  if (acc) {
    const gradeColor = acc.order.includes('FIRST') ? [0, 100, 0] : acc.order.includes('SECOND') ? [180, 130, 0] : [180, 0, 0]
    doc.setTextColor(...(gradeColor as [number, number, number]))
    doc.setFontSize(11)
    doc.text(`Accuracy: ${acc.order}`, 110, _yPos + 24)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(80, 80, 80)
    doc.text(acc.formula, 110, _yPos + 32)
  }
  _yPos += 44
}

function boundaryDescriptionSection(doc: jsPDF, data: SurveyReportData): void {
  sectionTitle(doc, 'Boundary Description', '5')
  if (data.parcel) {
    if (data.parcel.parcel_ref) {
      labelValue(doc, 'Parcel Reference', data.parcel.parcel_ref)
    }
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...AMBER)
    doc.text('Area:', 15, _yPos)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(30, 30, 30)
    const areaText = `${data.parcel.area_sqm.toFixed(4)} m²  |  ${data.parcel.area_ha.toFixed(6)} ha  |  ${data.parcel.area_acres.toFixed(4)} acres`
    doc.text(areaText, 35, _yPos)
    _yPos += 5
    labelValue(doc, 'Perimeter', `${data.parcel.perimeter_m.toFixed(3)} m`)
  }

  if (data.bearingSchedule && data.bearingSchedule.length > 0) {
    newPage(doc)
    autoTable(doc, {
      startY: _yPos,
      head: [['Line', 'Bearing', 'Distance (m)']],
      body: data.bearingSchedule.map((b: any) => [b.from === b.to ? b.from : `${b.from} → ${b.to}`, b.bearing, b.distance.toFixed(3)]),
      headStyles: { fillColor: DARK, textColor: AMBER, fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
      alternateRowStyles: { fillColor: LIGHT_GRAY },
      columnStyles: { 0: { fontStyle: 'bold' }, 1: { halign: 'center' }, 2: { halign: 'right' } },
      margin: { left: 15, right: 15 },
    })
    _yPos = (doc as any).lastAutoTable.finalY + 8
  }
}

function beaconDescriptionSection(doc: jsPDF, data: SurveyReportData): void {
  sectionTitle(doc, 'Beacon Description', '6')

  const beacons: BeaconDescription[] = data.beaconDescriptions || data.controlPoints.filter((p: any) => p.is_control).map((p: any) => ({
    name: p.name,
    easting: p.easting,
    northing: p.northing,
    elevation: p.elevation,
    description: p.monumentType || 'Concrete beacon',
    condition: 'Good',
    monumentType: p.monumentType || 'Concrete',
  }))

  if (beacons.length === 0) {
    bodyText(doc, 'No beacon descriptions available.')
    return
  }

  autoTable(doc, {
    startY: _yPos,
    head: [['Beacon', 'Easting (m)', 'Northing (m)', 'Elev. (m)', 'Monument', 'Condition', 'Description']],
    body: beacons.map((b: any) => [
      b.name,
      b.easting.toFixed(4),
      b.northing.toFixed(4),
      b.elevation != null ? b.elevation.toFixed(3) : '—',
      b.monumentType || '—',
      b.condition || 'Good',
      b.description || '—',
    ]),
    headStyles: { fillColor: DARK, textColor: AMBER, fontStyle: 'bold', fontSize: 7 },
    bodyStyles: { fontSize: 7, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: LIGHT_GRAY },
    columnStyles: {
      0: { fontStyle: 'bold' },
      1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' },
    },
    margin: { left: 15, right: 15 },
  })
  _yPos = (doc as any).lastAutoTable.finalY + 8
  bodyText(doc, 'All beacons are in good condition unless otherwise noted.')
}

function topographicFeaturesSection(doc: jsPDF, data: SurveyReportData): void {
  if (!data.spotLevels || data.spotLevels.length === 0) {
    sectionTitle(doc, 'Topographic Features', '7')
    bodyText(doc, 'No topographic detail (spot levels) recorded for this survey.')
    return
  }

  sectionTitle(doc, 'Digital Terrain Model / Topographic Features', '7')
  bodyText(doc, `Spot levels recorded at ${data.spotLevels.length} detail points. Elevations are relative to the survey datum.`)

  autoTable(doc, {
    startY: _yPos,
    head: [['Point', 'Easting (m)', 'Northing (m)', 'Elevation (m)']],
    body: data.spotLevels.map((s: any) => [s.name, s.easting.toFixed(4), s.northing.toFixed(4), s.elevation.toFixed(3)]),
    headStyles: { fillColor: DARK, textColor: AMBER, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: LIGHT_GRAY },
    columnStyles: { 0: { fontStyle: 'bold' }, 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
    margin: { left: 15, right: 15 },
  })
  _yPos = (doc as any).lastAutoTable.finalY + 8
}

function calculationMethodologySection(doc: jsPDF, data: SurveyReportData): void {
  sectionTitle(doc, 'Calculation Methodology', '8')
  bodyText(doc, 'Area computation was performed using the coordinate (Shoelace) formula applied to the boundary points in their observed sequence. This method provides an accurate area independent of the shape of the parcel.')
  _yPos += 2
  bodyText(doc, 'Traverse adjustment was performed using the Bowditch Rule (Compass Rule), which distributes the linear misclosure proportionally to the lengths of the traverse legs. This method is appropriate for surveys conducted with comparable instrument precision across all legs.')
  _yPos += 2
  if (data.traverse) {
    const acc = computeTraverseAccuracy(data.traverse.linearError, data.traverse.totalDistance)
    if (acc) {
      bodyText(doc, `The achieved accuracy order is ${acc.order}. The relative precision of 1:${Math.round(1 / data.traverse.precisionRatio)} satisfies the requirements for a ${data.project.survey_type || 'cadastral'} survey.`)
    }
  }
}

function authenticationSection(doc: jsPDF, data: SurveyReportData): void {
  sectionTitle(doc, "Surveyor's Declaration", '9')

  const certText = `I, ${data.project.surveyor_name || '[SURVEYOR NAME]'}, a Licensed Surveyor (LSK Licence No. ${data.project.surveyor_licence || '[LICENCE NUMBER]'}), hereby certify that the above survey has been carried out under my direct supervision in accordance with the Survey Act Cap. 299 and the Survey Regulations thereunder, and that the plan and computations hereon are correct.`

  bodyText(doc, certText)
  _yPos += 10

  newPage(doc)

  doc.setFontSize(9)
  doc.setTextColor(30, 30, 30)
  doc.setFont('helvetica', 'bold')
  doc.text('Surveyor Signature:', 15, _yPos)
  _yPos += 8
  doc.setDrawColor(150, 150, 150)
  doc.setLineWidth(0.3)
  doc.line(15, _yPos, 90, _yPos)
  doc.setFont('helvetica', 'normal')
  _yPos += 5
  doc.text(`${data.project.surveyor_name || '________________'}`, 15, _yPos)
  _yPos += 5
  doc.text(`LSK Licence No.: ${data.project.surveyor_licence || '________________'}`, 15, _yPos)
  _yPos += 5
  doc.text(`Date: _____________________________`, 15, _yPos)

  _yPos += 15
  doc.setFont('helvetica', 'bold')
  doc.text('Firm / Organisation:', 15, _yPos)
  _yPos += 8
  doc.setFont('helvetica', 'normal')
  doc.text(`${data.project.firm_name || '________________'}`, 15, _yPos)
  _yPos += 5
  doc.text(`${data.project.firm_address || '________________'}`, 15, _yPos)
}

function appendicesSection(doc: jsPDF): void {
  sectionTitle(doc, 'Appendices', '10')

  const appendices = [
    ['A', 'Field Notes Reference', 'Pages: ____'],
    ['B', 'Computation Sheets Reference', 'Pages: ____'],
    ['C', "Observer's Field Book Reference", 'Pages: ____'],
    ['D', 'Calibration Certificates Reference', 'Pages: ____'],
  ]

  autoTable(doc, {
    startY: _yPos,
    head: [['Appendix', 'Description', 'Reference']],
    body: appendices,
    headStyles: { fillColor: DARK, textColor: AMBER, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 15, right: 15 },
  })
  _yPos = (doc as any).lastAutoTable.finalY + 8
}

function mobilisationSection(doc: jsPDF, m: MobilisationData): void {
  sectionTitle(doc, 'Mobilisation Report', 'M')
  const rows: [string, string][] = [
    ['Instrument', m.instrument],
    ['Serial Number', m.serialNumber],
    ['Calibration Date', m.calibrationDate],
    ['Field Team', m.fieldTeam],
    ['Weather Conditions', m.weather],
    ['Date of Survey', m.surveyDate],
    ['Site Access', m.siteAccess || '—'],
  ]
  for (const [l, v] of rows) {
    labelValue(doc, l, v)
  }
}

function photosSection(doc: jsPDF, photos: Photo[]): void {
  sectionTitle(doc, 'Field Photographs', 'P')
  bodyText(doc, `The following ${photos.length} field photograph(s) were taken during the survey.`)
  _yPos += 4

  const cols = photos.length >= 4 ? 2 : 1
  const imgW = cols === 2 ? 85 : 175
  const imgH = imgW * 0.75

  for (let i = 0; i < photos.length; i += cols) {
    newPage(doc)
    const row = photos.slice(i, i + cols)
    for (let j = 0; j < row.length; j++) {
      const photo = row[j]
      try {
        doc.addImage(photo.url, 'JPEG', 15 + j * (imgW + 5), _yPos, imgW, imgH)
        _yPos += imgH + 4
        doc.setFontSize(8)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...AMBER)
        doc.text(`Photo ${i + j + 1}`, 15 + j * (imgW + 5), _yPos)
        _yPos += 4
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(30, 30, 30)
        const caption = photo.caption || 'Field photograph'
        const captionLines = doc.splitTextToSize(caption, imgW)
        doc.text(captionLines, 15 + j * (imgW + 5), _yPos)
        _yPos += captionLines.length * 4
        if (photo.orientation) {
          doc.setFontSize(7)
          doc.setTextColor(120, 120, 120)
          doc.text(`View: ${photo.orientation}`, 15 + j * (imgW + 5), _yPos)
          _yPos += 4
        }
      } catch {
        doc.setFontSize(9)
        doc.setTextColor(120, 120, 120)
        doc.text(`[Photo ${i + j + 1}: ${photo.caption || 'image unavailable'}]`, 15, _yPos)
        _yPos += 8
      }
    }
    if (cols === 2) _yPos += imgH
  }
}

export function generateSurveyReport(
  data: SurveyReportData,
  opts: SurveyReportOptions = {},
  onBlob?: (blob: Blob, filename: string) => void
): void {
  // Pass submission_number to footers
  const pageFooterOpts = { submission_number: opts.submission_number }
  reset()
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  coverPage(doc, data, opts)

  addPageFooter(doc)
  doc.addPage()
  _currentPage++

  tableOfContents(doc, data)

  addPageFooter(doc)
  doc.addPage()
  _currentPage++
  _yPos = 20

  introductionSection(doc, data, opts)
  methodologySection(doc, data)
  controlNetworkSection(doc, data)

  if (data.traverse) {
    traverseComputationSection(doc, data)
  }

  boundaryDescriptionSection(doc, data)
  beaconDescriptionSection(doc, data)
  topographicFeaturesSection(doc, data)
  calculationMethodologySection(doc, data)
  authenticationSection(doc, data)
  appendicesSection(doc)

  if (opts.includeMobilisation && data.mobilisation) {
    addPageFooter(doc)
    doc.addPage()
    _currentPage++
    _yPos = 20
    mobilisationSection(doc, data.mobilisation)
  }

  if (opts.includePhotos && data.photos?.length) {
    addPageFooter(doc)
    doc.addPage()
    _currentPage++
    _yPos = 20
    photosSection(doc, data.photos)
  }

  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addPageFooter(doc)
  }

  const date = new Date().toISOString().slice(0, 10)
  const filename = `${data.project.name.replace(/\s+/g, '_')}_Survey_Report_${date}.pdf`

  if (onBlob) {
    const blob = doc.output('blob')
    onBlob(blob, filename)
  } else {
    doc.save(filename)
  }
}
