import type { CapacitorConfig } from '@capacitor/cli'

/**
 * METARDU Capacitor Configuration
 *
 * AUDIT FIX (H5, 2026-07-03): Capacitor dependencies were installed
 * but no config file existed — `npm run mobile:build` and `npm run
 * mobile:sync` would fail. This config enables building METARDU as
 * a native Android (and future iOS) app wrapping the Next.js PWA.
 *
 * Build steps:
 *   1. npm run build              # build the Next.js app
 *   2. npx cap sync               # sync web assets to native projects
 *   3. npx cap open android       # open in Android Studio
 *   4. Build APK in Android Studio
 *
 * The app uses:
 *   - @capacitor/geolocation for GPS positioning
 *   - @capacitor-community/bluetooth-le for total station connection
 *   - @capacitor/filesystem for offline data storage
 *
 * Permissions (AndroidManifest.xml is auto-generated by Capacitor):
 *   - ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION
 *   - BLUETOOTH, BLUETOOTH_ADMIN, BLUETOOTH_CONNECT
 *   - INTERNET, ACCESS_NETWORK_STATE
 */

const config: CapacitorConfig = {
  appId: 'com.metardu.app',
  appName: 'METARDU',
  webDir: 'out',  // Next.js static export output directory
  backgroundColor: '#0a0e14',  // dark theme background
  server: {
    androidScheme: 'https',
    // For development, point to the dev server:
    // url: 'http://192.168.1.100:3000',
    // cleartext: true,
  },
  android: {
    allowMixedContent: false,
    backgroundColor: '#0a0e14',
    captureInput: true,
    webContentsDebuggingEnabled: false,
  },
  plugins: {
    Geolocation: {
      // Request foreground location permissions
      permissions: ['location'],
    },
    SplashScreen: {
      launchShowDuration: 2000,
      backgroundColor: '#0a0e14',
      androidSplashResourceName: 'splash',
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      androidSpinnerStyle: 'large',
      iosSpinnerStyle: 'small',
      spinnerColor: '#f59e0b',
      splashFullScreen: true,
      splashImmersive: true,
    },
    CapacitorHttp: {
      enabled: true,  // allow HTTP requests from the native app
    },
  },
}

export default config
