module.exports = {
  apps: [
    {
      name: 'metardu',
      script: '.next/standalone/server.js',
      cwd: '/home/mohameddosho20/metardu',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NODE_OPTIONS: '--max-old-space-size=768',
      },
      max_memory_restart: '900M',
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      min_uptime: '10s',
      max_restarts: 5,
      exp_backoff_restart_delay: 100,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      out_file: '/home/mohameddosho20/.pm2/logs/metardu-out.log',
      error_file: '/home/mohameddosho20/.pm2/logs/metardu-error.log',
      merge_logs: true,
      listen_timeout: 30000,
      kill_timeout: 10000,
      wait_ready: false,
    },
  ],
}
