/**
 * ⚠️  DEPRECATED — DO NOT EDIT THIS FILE.
 *
 * The active Tailwind config is tailwind.config.ts (TypeScript version).
 * Next.js + shadcn/ui resolves tailwind.config.ts first.
 *
 * This file is kept to avoid breaking any tooling that expects a .js config.
 * All theme changes go in tailwind.config.ts.
 */
module.exports = require('./tailwind.config.ts')

