'use client'

import { Download } from 'lucide-react'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ValidationResult } from '@/types/cadastra'
import { usePrint, PrintButton, PrintHeader } from '@/hooks/usePrint'

interface ValidationReportProps {
  result: ValidationResult
  projectId: string
}

export default function ValidationReport({ result, projectId }: ValidationReportProps) {
  const { print, isPrinting, paperSize, setPaperSize, orientation, setOrientation } = usePrint({ title: 'Cadastral Validation Report' })
  const generatePDF = () => {
    const doc = new jsPDF()
    
    doc.setFontSize(18)
    doc.text('CadastraAI Validator Report', 14, 20)
    
    doc.setFontSize(11)
    doc.text(`Project: ${projectId}`, 14, 30)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 36)
    doc.text(`Dispute Probability Score: ${result.score}/100`, 14, 42)
    doc.text(`Risk Level: ${result.summary.risk_level.toUpperCase()}`, 14, 48)
    
    doc.setFontSize(12)
    doc.text('Summary', 14, 60)
    doc.setFontSize(10)
    doc.text(`Total Boundary Area: ${result.summary.boundary_area} m²`, 14, 68)
    doc.text(`Total Overlap Area: ${result.summary.total_overlap_area} m²`, 14, 74)
    doc.text(`Total Gap Area: ${result.summary.total_gap_area} m²`, 14, 80)
    
    if (result.overlaps.length > 0) {
      doc.setFontSize(12)
      doc.text('Overlaps Detected', 14, 94)
      autoTable(doc, {
        startY: 100,
        head: [['ID', 'Area (m²)', 'Severity', 'Description']],
        body: result.overlaps.map((o: any) => [o.id, String(o.area), o.severity, o.description])
      })
    }
    
    if (result.gaps.length > 0) {
      const startY = result.overlaps.length > 0 ? (doc as any).lastAutoTable.finalY + 15 : 120
      doc.setFontSize(12)
      doc.text('Gaps Detected', 14, startY)
      autoTable(doc, {
        startY: startY + 6,
        head: [['ID', 'Area (m²)', 'Severity', 'Description']],
        body: result.gaps.map((g: any) => [g.id, String(g.area), g.severity, g.description])
      })
    }
    
    doc.setFontSize(8)
    doc.text('Generated by Metardu - CadastraAI Validator', 14, 280)
    doc.text('This report is for informational purposes only.', 14, 286)
    
    doc.save('cadastra-validation-report.pdf')
  }
  
  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg p-6">
      <PrintHeader title="Cadastral Validation Report" subtitle={`Project: ${projectId}`} />
      <h3 className="text-lg font-semibold mb-4">Generate Report</h3>
      
      <div className="flex items-center gap-3 no-print print-hide">
        <button
          onClick={generatePDF}
          className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          <Download className="h-5 w-5" />
          Download PDF Report
        </button>
        <PrintButton
          print={print}
          isPrinting={isPrinting}
          paperSize={paperSize}
          setPaperSize={setPaperSize}
          orientation={orientation}
          setOrientation={setOrientation}
          printTitle="Cadastral Validation Report"
          printSubtitle={`Project: ${projectId}`}
        />
      </div>
    </div>
  )
}