/**
 * Survey-type-specific DOCX templates
 * Each survey type has customized sections and content
 */

import type { SectionContent } from '@/types/surveyReport'
import type { SurveyType } from '@/types/project'

export interface SurveyTypeTemplate {
  type: SurveyType
  sections: Array<{
    section: SectionContent['section']
    title: string
    content: string | ((data: any) => string)
    autoGenerated: boolean
  }>
}

const cadastralTemplate: SurveyTypeTemplate = {
  type: 'cadastral',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>CADASTRAL SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Client:</strong> {clientName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>This report documents the cadastral (boundary) survey carried out at {projectLocation}. The survey was conducted to establish boundaries and prepare a cadastral plan per Survey Act (Cap. 299) and Survey Regulations 1994.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<p>Scope included:</p>
        <ul>
          <li>Reconnaissance and identification of existing boundary marks</li>
          <li>Establishment of control survey network</li>
          <li>Boundary tracing and verification</li>
          <li>Measurement using Total Station/GNSS</li>
          <li>Computation of areas and survey plan preparation</li>
        </ul>`,
    },
    {
      section: 'CONTROL_SURVEY',
      title: 'Control Survey',
      autoGenerated: false,
      content: `<p>Control established using GNSS/Total Station. Control points coordinated in UTM Zone 36S, Datum WGS84. Network adjusted using least squares method.</p>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Accuracy',
      autoGenerated: false,
      content: `<p><strong>Accuracy Achieved:</strong></p>
        <ul>
          <li>Angular misclosure: Within allowable limits</li>
          <li>Linear precision: 1:{precisionRatio}</li>
          <li>Area accuracy: Computed using Simpson's Rule</li>
        </ul>
        <p>Standards meet cadastral survey requirements.</p>`,
    },
  ],
}

const topographicTemplate: SurveyTypeTemplate = {
  type: 'topographic',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>TOPOGRAPHIC SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Area:</strong> {areaHectares} Ha</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Topographic survey at {projectLocation} to capture terrain features, elevations, and planimetric details for engineering design. Executed per RDM Volume 1.1 standards.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<p>Services included:</p>
        <ul>
          <li>Horizontal and vertical control establishment</li>
          <li>Ground levels on {pointSpacing} grid</li>
          <li>Mapping of features (buildings, roads, drainage, utilities)</li>
          <li>Cross-sections along existing features</li>
          <li>Digital terrain model (DTM) generation</li>
          <li>Contour maps at {contourInterval} intervals</li>
        </ul>`,
    },
    {
      section: 'EQUIPMENT_AND_PERSONNEL',
      title: 'Equipment and Personnel',
      autoGenerated: false,
      content: `<p><strong>Equipment:</strong> GNSS RTK, Total Station (1" accuracy), Auto Level, Civil 3D/ArcGIS</p>`,
    },
    {
      section: 'DATA_PROCESSING',
      title: 'Data Processing',
      autoGenerated: true,
      content: `<ol>
          <li>Field data downloaded and backed up daily</li>
          <li>GNSS baselines processed</li>
          <li>Total Station data imported to Civil 3D for DTM</li>
          <li>Contours generated</li>
          <li>Quality check against control</li>
        </ol>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Accuracy',
      autoGenerated: false,
      content: `<p><strong>Accuracy:</strong> Horizontal: ±{horizontalAccuracy}, Vertical: ±{verticalAccuracy}, Point density: {pointDensity}</p>`,
    },
  ],
}

const engineeringTemplate: SurveyTypeTemplate = {
  type: 'engineering',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>ENGINEERING SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Contract No:</strong> {contractNumber}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Engineering survey for {projectName} at {projectLocation}. Supports {projectPurpose} activities.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>Construction control network</li>
          <li>Setting out per design drawings</li>
          <li>As-built surveys</li>
          <li>Volume calculations for earthworks</li>
          <li>Deformation monitoring</li>
        </ul>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Accuracy',
      autoGenerated: false,
      content: `<p><strong>Tolerances:</strong> Structural: ±{structuralTolerance}, Earthworks: ±{earthworksTolerance}, As-built: ±{asBuiltTolerance}</p>`,
    },
  ],
}

const miningTemplate: SurveyTypeTemplate = {
  type: 'mining',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>MINING SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Mineral:</strong> {mineralType}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Mining survey at {projectLocation} supporting {projectPurpose} activities.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>Mining control network</li>
          <li>Topographic survey of mining area</li>
          <li>Stockpile volume measurements</li>
          <li>Pit surveying and volumes</li>
          <li>Tailings dam surveys</li>
          <li>Rehabilitation monitoring</li>
        </ul>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Volume Calculations',
      autoGenerated: false,
      content: `<p><strong>Stockpile Volumes:</strong> Stockpile ID: {stockpileId}, Volume: {stockpileVolume} m³, Material: {materialType}</p>
      <p>Method: Grid method with {gridSpacing} spacing, cross-checked with drone photogrammetry.</p>`,
    },
  ],
}

const defaultTemplate: SurveyTypeTemplate = {
  type: 'geodetic',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Client:</strong> {clientName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Survey report for {projectLocation}.</p>`,
    },
  ],
}

const TEMPLATES: Record<SurveyType, SurveyTypeTemplate> = {
  cadastral: cadastralTemplate,
  topographic: topographicTemplate,
  engineering: engineeringTemplate,
  mining: miningTemplate,
  geodetic: defaultTemplate,
  hydrographic: defaultTemplate,
  drone: defaultTemplate,
  deformation: defaultTemplate,
}

export function getTemplateByType(type: SurveyType): SurveyTypeTemplate {
  return TEMPLATES[type] || defaultTemplate
}

export function interpolateTemplate(template: string, data: any): string {
  return template.replace(/{(\w+)}/g, (match, key) => {
    return (data as any)[key] || match
  })
}

export function getTemplateSections(type: SurveyType, data: any): SectionContent[] {
  const template = getTemplateByType(type)
  
  return template.sections.map((s, index) => {
    const contentStr = typeof s.content === 'function' ? s.content(data) : s.content
    const interpolated = interpolateTemplate(contentStr, data)
    
    return {
      section: s.section,
      sectionNumber: index + 1,
      title: s.title,
      content: interpolated,
      autoGenerated: s.autoGenerated,
      completeness: 100,
    }
  })
}

export default getTemplateByType
