/**
 * Survey-type-specific DOCX templates
 * Each survey type has customized sections and content
 */

import type { SectionContent } from '@/types/surveyReport'
import type { SurveyType } from '@/types/project'

export interface SurveyTypeTemplate {
  type: SurveyType
  sections: Array<{
    section: SectionContent['section']
    title: string
    content: string | ((data: any) => string)
    autoGenerated: boolean
  }>
}

const cadastralTemplate: SurveyTypeTemplate = {
  type: 'cadastral',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>CADASTRAL SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Client:</strong> {clientName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>This report documents the cadastral (boundary) survey carried out at {projectLocation}. The survey was conducted to establish boundaries and prepare a cadastral plan per Survey Act (Cap. 299) and Survey Regulations 1994.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<p>Scope included:</p>
        <ul>
          <li>Reconnaissance and identification of existing boundary marks</li>
          <li>Establishment of control survey network</li>
          <li>Boundary tracing and verification</li>
          <li>Measurement using Total Station/GNSS</li>
          <li>Computation of areas and survey plan preparation</li>
        </ul>`,
    },
    {
      section: 'CONTROL_SURVEY',
      title: 'Control Survey',
      autoGenerated: false,
      content: `<p>Control established using GNSS/Total Station. Control points coordinated in UTM Zone 36S, Datum WGS84. Network adjusted using least squares method.</p>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Accuracy',
      autoGenerated: false,
      content: `<p><strong>Accuracy Achieved:</strong></p>
        <ul>
          <li>Angular misclosure: Within allowable limits</li>
          <li>Linear precision: 1:{precisionRatio}</li>
          <li>Area accuracy: Computed using Simpson's Rule</li>
        </ul>
        <p>Standards meet cadastral survey requirements.</p>`,
    },
  ],
}

const topographicTemplate: SurveyTypeTemplate = {
  type: 'topographic',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>TOPOGRAPHIC SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Area:</strong> {areaHectares} Ha</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Topographic survey at {projectLocation} to capture terrain features, elevations, and planimetric details for engineering design. Executed per RDM Volume 1.1 standards.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<p>Services included:</p>
        <ul>
          <li>Horizontal and vertical control establishment</li>
          <li>Ground levels on {pointSpacing} grid</li>
          <li>Mapping of features (buildings, roads, drainage, utilities)</li>
          <li>Cross-sections along existing features</li>
          <li>Digital terrain model (DTM) generation</li>
          <li>Contour maps at {contourInterval} intervals</li>
        </ul>`,
    },
    {
      section: 'EQUIPMENT_AND_PERSONNEL',
      title: 'Equipment and Personnel',
      autoGenerated: false,
      content: `<p><strong>Equipment:</strong> GNSS RTK, Total Station (1" accuracy), Auto Level, Civil 3D/ArcGIS</p>`,
    },
    {
      section: 'DATA_PROCESSING',
      title: 'Data Processing',
      autoGenerated: true,
      content: `<ol>
          <li>Field data downloaded and backed up daily</li>
          <li>GNSS baselines processed</li>
          <li>Total Station data imported to Civil 3D for DTM</li>
          <li>Contours generated</li>
          <li>Quality check against control</li>
        </ol>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Accuracy',
      autoGenerated: false,
      content: `<p><strong>Accuracy:</strong> Horizontal: ±{horizontalAccuracy}, Vertical: ±{verticalAccuracy}, Point density: {pointDensity}</p>`,
    },
  ],
}

const engineeringTemplate: SurveyTypeTemplate = {
  type: 'engineering',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>ENGINEERING SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Contract No:</strong> {contractNumber}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Engineering survey for {projectName} at {projectLocation}. Supports {projectPurpose} activities.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>Construction control network</li>
          <li>Setting out per design drawings</li>
          <li>As-built surveys</li>
          <li>Volume calculations for earthworks</li>
          <li>Deformation monitoring</li>
        </ul>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Accuracy',
      autoGenerated: false,
      content: `<p><strong>Tolerances:</strong> Structural: ±{structuralTolerance}, Earthworks: ±{earthworksTolerance}, As-built: ±{asBuiltTolerance}</p>`,
    },
  ],
}

const miningTemplate: SurveyTypeTemplate = {
  type: 'mining',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>MINING SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Mineral:</strong> {mineralType}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Mining survey at {projectLocation} supporting {projectPurpose} activities.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>Mining control network</li>
          <li>Topographic survey of mining area</li>
          <li>Stockpile volume measurements</li>
          <li>Pit surveying and volumes</li>
          <li>Tailings dam surveys</li>
          <li>Rehabilitation monitoring</li>
        </ul>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Volume Calculations',
      autoGenerated: false,
      content: `<p><strong>Stockpile Volumes:</strong> Stockpile ID: {stockpileId}, Volume: {stockpileVolume} m³, Material: {materialType}</p>
      <p>Method: Grid method with {gridSpacing} spacing, cross-checked with drone photogrammetry.</p>`,
    },
  ],
}

const geodeticTemplate: SurveyTypeTemplate = {
  type: 'geodetic',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>GEODETIC CONTROL SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Network Type:</strong> {networkType}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>This report documents geodetic control survey works establishing {networkOrder} order control network at {projectLocation}. The survey complies with FGCC standards for {networkOrder} order control.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>Reconnaissance and site selection</li>
          <li>Monument construction ({monumentType})</li>
          <li>GNSS observations ({sessionDuration} hour sessions)</li>
          <li>Baseline processing and network adjustment</li>
          <li>Leveling to {verticalOrder} order standards</li>
        </ul>`,
    },
    {
      section: 'CONTROL_SURVEY',
      title: 'Control Network',
      autoGenerated: false,
      content: `<p><strong>Network Statistics:</strong></p>
        <ul>
          <li>Number of stations: {stationCount}</li>
          <li>Number of baselines: {baselineCount}</li>
          <li>Reference ellipsoid: {ellipsoid}</li>
          <li>Projection: {projection}</li>
          <li>Datum: {datum}</li>
        </ul>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Accuracy',
      autoGenerated: false,
      content: `<p><strong>Accuracy Achieved:</strong></p>
        <ul>
          <li>Horizontal: ±{horizontalAccuracy} ppm</li>
          <li>Vertical: ±{verticalAccuracy} ppm</li>
          <li>Reference frame: {referenceFrame}</li>
        </ul>
        <p>Network meets {networkOrder} order accuracy per FGCC/NGS standards.</p>`,
    },
  ],
}

const hydrographicTemplate: SurveyTypeTemplate = {
  type: 'hydrographic',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>HYDROGRAPHIC SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Water Body:</strong> {waterBodyName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Survey Type:</strong> {surveyPurpose}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Hydrographic survey of {waterBodyName} conducted for {surveyPurpose}. Survey executed per IHO S-44 Order {surveyOrder} standards.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>Shoreline mapping</li>
          <li>Bathymetric data acquisition ({lineSpacing} spacing)</li>
          <li>Water level monitoring</li>
          <li>Velocity of sound profiling</li>
          <li>Tide gauge installation and monitoring</li>
          <li>Data processing and chart production</li>
        </ul>`,
    },
    {
      section: 'EQUIPMENT_AND_PERSONNEL',
      title: 'Equipment',
      autoGenerated: false,
      content: `<p><strong>Survey Equipment:</strong></p>
        <ul>
          <li>Multibeam Echosounder: {multibeamModel}</li>
          <li>Singlebeam Echosounder: {singlebeamModel}</li>
          <li>GNSS-IMU: {gnssImuModel}</li>
          <li>Sound Velocity Profiler: {svpModel}</li>
          <li>Software: {processingSoftware}</li>
        </ul>`,
    },
    {
      section: 'DATA_PROCESSING',
      title: 'Data Processing',
      autoGenerated: true,
      content: `<ol>
          <li>Raw data downloaded and backed up</li>
          <li>Sound velocity corrections applied</li>
          <li>Tidal corrections applied</li>
          <li>Bathymetric surface generated ({gridSize}m resolution)</li>
          <li>Quality assurance checks</li>
        </ol>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results',
      autoGenerated: false,
      content: `<p><strong>Survey Statistics:</strong></p>
        <ul>
          <li>Area surveyed: {areaCovered} hectares</li>
          <li>Line km: {lineKm} km</li>
          <li>Depth range: {minDepth}m to {maxDepth}m</li>
          <li>Vertical uncertainty: ±{verticalUncertainty}m</li>
          <li>Horizontal uncertainty: ±{horizontalUncertainty}m</li>
        </ul>`,
    },
  ],
}

const droneTemplate: SurveyTypeTemplate = {
  type: 'drone',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>DRONE SURVEY REPORT (UAV Photogrammetry)</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Project:</strong> {projectName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Drone:</strong> {droneModel}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>UAV photogrammetric survey conducted at {projectLocation} using {droneModel}. Products include orthophoto, DSM, DTM, and point cloud.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>GCP planning and survey (Total Station/GNSS)</li>
          <li>UAV flight planning ({altitude}m AGL, {overlap}% overlap)</li>
          <li>Image acquisition ({imageCount} images)</li>
          <li>Photogrammetric processing (SfM/MVS)</li>
          <li>Orthomosaic generation</li>
          <li>DSM/DTM production</li>
        </ul>`,
    },
    {
      section: 'EQUIPMENT_AND_PERSONNEL',
      title: 'Equipment',
      autoGenerated: false,
      content: `<p><strong>Equipment Used:</strong></p>
        <ul>
          <li>UAV: {droneModel} ({cameraResolution}MP camera)</li>
          <li>GCP Survey: {gnssModel} RTK</li>
          <li>Processing: {processingSoftware}</li>
        </ul>`,
    },
    {
      section: 'DATA_PROCESSING',
      title: 'Data Processing',
      autoGenerated: true,
      content: `<ol>
          <li>GCP coordinates computed</li>
          <li>Image alignment (Structure from Motion)</li>
          <li>Point cloud generation ({pointCount} points)</li>
          <li>Mesh and texture generation</li>
          <li>Orthomosaic production</li>
          <li>Accuracy assessment using check points</li>
        </ol>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Accuracy Assessment',
      autoGenerated: false,
      content: `<p><strong>Deliverables:</strong></p>
        <ul>
          <li>Orthophoto: {orthoResolution} cm/pixel</li>
          <li>DSM: {dsmResolution} cm/pixel</li>
          <li>Point Cloud: {pointDensity} points/m²</li>
        </ul>
        <p><strong>Accuracy (RMSE):</strong></p>
        <ul>
          <li>Horizontal: ±{horizontalRmse}m</li>
          <li>Vertical: ±{verticalRmse}m</li>
        </ul>`,
    },
  ],
}

const deformationTemplate: SurveyTypeTemplate = {
  type: 'deformation',
  sections: [
    {
      section: 'TITLE_PAGE',
      title: 'Title Page',
      autoGenerated: true,
      content: `<h1>DEFORMATION MONITORING SURVEY REPORT</h1>
        <p><strong>Report No:</strong> {reportNumber}</p>
        <p><strong>Structure:</strong> {structureName}</p>
        <p><strong>Location:</strong> {projectLocation}</p>
        <p><strong>Monitoring Period:</strong> {monitoringPeriod}</p>
        <p><strong>Date:</strong> {date}</p>`,
    },
    {
      section: 'INTRODUCTION',
      title: 'Introduction',
      autoGenerated: false,
      content: `<p>Deformation monitoring survey of {structureName} at {projectLocation}. Monitoring conducted to detect and quantify structural movement over {monitoringPeriod}.</p>`,
    },
    {
      section: 'SCOPE_OF_WORK',
      title: 'Scope of Work',
      autoGenerated: false,
      content: `<ul>
          <li>Establishment of stable reference points</li>
          <li>Installation of monitoring prisms ({prismCount} points)</li>
          <li>Periodic observations ({frequency})</li>
          <li>Data analysis and trend detection</li>
          <li>Alert threshold monitoring</li>
          <li>Reporting</li>
        </ul>`,
    },
    {
      section: 'EQUIPMENT_AND_PERSONNEL',
      title: 'Equipment',
      autoGenerated: false,
      content: `<p><strong>Monitoring Equipment:</strong></p>
        <ul>
          <li>Robotic Total Station: {rtsModel} ({accuracy})</li>
          <li>Auto Prism: {prismType}</li>
          <li>GNSS Sensors: {gnssModel} (if applicable)</li>
          <li>Inclinometers: {inclinometerModel} (if applicable)</li>
        </ul>`,
    },
    {
      section: 'DATA_PROCESSING',
      title: 'Data Analysis',
      autoGenerated: true,
      content: `<ol>
          <li>Raw observations downloaded</li>
          <li>Network adjustment per epoch</li>
          <li>Displacement calculation (3D)</li>
          <li>Statistical analysis (trend, velocity, acceleration)</li>
          <li>Threshold comparison</li>
          <li>Visualization (time series, vectors)</li>
        </ol>`,
    },
    {
      section: 'RESULTS_AND_ACCURACY',
      title: 'Results and Findings',
      autoGenerated: false,
      content: `<p><strong>Monitoring Summary:</strong></p>
        <ul>
          <li>Monitoring period: {startDate} to {endDate}</li>
          <li>Number of epochs: {epochCount}</li>
          <li>Maximum horizontal displacement: {maxHorizontal}mm</li>
          <li>Maximum vertical displacement: {maxVertical}mm</li>
          <li>Alert status: {alertStatus}</li>
        </ul>
        <p><strong>Conclusion:</strong> {conclusion}</p>`,
    },
  ],
}

const TEMPLATES: Record<SurveyType, SurveyTypeTemplate> = {
  cadastral: cadastralTemplate,
  topographic: topographicTemplate,
  engineering: engineeringTemplate,
  mining: miningTemplate,
  geodetic: geodeticTemplate,
  hydrographic: hydrographicTemplate,
  drone: droneTemplate,
  deformation: deformationTemplate,
}

export function getTemplateByType(type: SurveyType): SurveyTypeTemplate {
  return TEMPLATES[type] || geodeticTemplate
}

export function interpolateTemplate(template: string, data: any): string {
  return template.replace(/{(\w+)}/g, (match, key) => {
    return (data as any)[key] || match
  })
}

export function getTemplateSections(type: SurveyType, data: any): SectionContent[] {
  const template = getTemplateByType(type)
  
  return template.sections.map((s, index) => {
    const contentStr = typeof s.content === 'function' ? s.content(data) : s.content
    const interpolated = interpolateTemplate(contentStr, data)
    
    return {
      section: s.section,
      sectionNumber: index + 1,
      title: s.title,
      content: interpolated,
      autoGenerated: s.autoGenerated,
      completeness: 100,
    }
  })
}

export default getTemplateByType
