export type ReportSection =
  | 'TITLE_PAGE'
  | 'TABLE_OF_CONTENTS'
  | 'INTRODUCTION'
  | 'SCOPE_OF_WORK'
  | 'EQUIPMENT_AND_PERSONNEL'
  | 'CONTROL_SURVEY'
  | 'TOPOGRAPHIC_SURVEY'
  | 'DATA_PROCESSING'
  | 'RESULTS_AND_ACCURACY'
  | 'COORDINATE_REGISTER'
  | 'BENCHMARK_REGISTER'
  | 'TRAVERSE_COMPUTATIONS'
  | 'LEVELLING_COMPUTATIONS'
  | 'CONCLUSIONS_AND_RECOMMENDATIONS'

export interface SurveyReportInput {
  projectId: string

  reportTitle: string
  contractNumber?: string
  clientName: string
  clientAddress: string
  firmName: string
  firmAddress: string
  firmIskNumber: string
  surveyorName: string
  surveyorRegistrationNumber?: string
  surveyorIskNumber: string
  reportDate: string
  reportNumber: string
  submissionNumber?: string
  revisionNumber: string
  revisionDate?: string

  projectLocation: string
  county: string
  constituency?: string
  projectPurpose: string
  siteDescription: string
  surveyPeriodStart: string
  surveyPeriodEnd: string

  scopeItems: string[]

  equipment: EquipmentItem[]
  personnel: PersonnelItem[]

  datum: 'ARC1960' | 'WGS84'
  projection: string
  controlPoints: ControlPoint[]
  gnssMethod?: string
  baseStationName?: string
  baseStationCoords?: { easting: number; northing: number; elevation: number }

  surveyMethod: 'TOTAL_STATION' | 'GNSS_RTK' | 'LEVEL' | 'COMBINED'
  instrumentUsed: string
  pointDensity?: string
  areaHectares?: number

  traverseAccuracy?: string
  levellingMisclosure?: string
  gnssBaselineRMS?: string

  levellingRuns?: LevellingRun[]

  conclusions: string[]
  recommendations: string[]
}

export interface EquipmentItem {
  type: string
  make: string
  serialNumber: string
  calibrationDate: string
  calibrationCert: string
}

export interface PersonnelItem {
  name: string
  role: string
  qualification: string
}

export interface ControlPoint {
  id: string
  order: 'PRIMARY' | 'SECONDARY' | 'TERTIARY'
  easting: number
  northing: number
  elevation: number
  source: 'GNSS' | 'TOTAL_STATION' | 'EXISTING'
  description: string
  markType: string
}

export interface LevellingRun {
  runId: string
  fromBM: string
  toBM: string
  distance: number
  misclosure: number
  allowable: number
  passes: boolean
}

export interface SurveyReportOutput {
  sections: SectionContent[]
  wordDocBase64?: string
  pdfBase64?: string
}

export interface SectionContent {
  section: ReportSection
  sectionNumber: number
  title: string
  content: string
  autoGenerated: boolean
  completeness: number
}

export interface ReportCompletenessResult {
  overallPercent: number
  sectionsComplete: number
  sectionsIncomplete: SectionGap[]
  readyToFinalise: boolean
}

export interface SectionGap {
  section: ReportSection
  sectionNumber: number
  missingFields: string[]
  completeness: number
}

export interface SurveyReportDocument {
  id: string
  projectId: string
  userId: string
  reportNumber: string
  reportTitle: string
  revision: string
  status: 'draft' | 'review' | 'finalised'
  inputData: SurveyReportInput
  sections: SectionContent[]
  completeness: number
  createdAt: string
  updatedAt: string
}

export interface SurveyReportSummary {
  id: string
  reportNumber: string
  reportTitle: string
  revision: string
  status: string
  completeness: number
  createdAt: string
  updatedAt: string
}
