import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://metardu.duckdns.org'

  const routes = [
    '',
    '/login',
    '/register',
    '/pricing',
    '/community',
    '/help',
    '/map',
    '/fieldbook',
    '/cadastral-workflow',
    '/tools/topology-check',
    '/tools/subdivision-generator',
    '/tools/cogo-reconstruct',
    '/tools/as-built-deviation',
    '/tools/scale-factor',
    '/tools/site-calibration',
    '/tools/orthometric-height',
    '/tools/volume-comparison',
    '/tools/lsa',
    '/tools/gnss-baseline',
    '/tools/road-design',
    '/tools/cut-fill',
    '/tools/pile-grid',
    '/tools/machine-control',
    '/tools/progress-monitor',
    '/tools/statutory-workbook',
    '/tools/survey-plan-demo',
    '/tools/billable-documents',
    '/tools/cassini-utm',
    '/tools/level-book',
    '/tools/traverse-field-book',
    '/tools/point-cloud-import',
    '/tools/orthophoto-viewer',
    '/engineering-workflow',
    '/topographic-workflow',
    '/tools/all',
    '/tools/cogo',
    '/tools/traverse',
    '/tools/leveling',
    '/tools/coordinates',
    '/tools/area',
    '/tools/distance',
    '/tools/bearing',
    '/tools/curves',
    '/tools/cut-fill',
    '/tools/deformation',
    '/tools/gcp-optimizer',
    '/tools/lsa',
    '/field-records',
    '/report-templates',
    '/sectional',
    '/marketplace',
    '/beacons',
    '/analytics',
    '/docs',
    '/docs/quick-start',
    '/docs/first-plan',
  ]

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '' ? 'daily' : 'weekly',
    priority: route === '' ? 1.0 : route.startsWith('/tools') ? 0.7 : 0.8,
  }))
}
