import type {
  SurveyReportInput,
  SectionContent,
  ControlPoint,
  LevellingRun,
  ReportSection
} from '@/types/surveyReport'

const SECTION_TITLES: Record<ReportSection, { number: number; title: string }> = {
  TITLE_PAGE: { number: 1, title: 'Title Page' },
  TABLE_OF_CONTENTS: { number: 2, title: 'Table of Contents' },
  INTRODUCTION: { number: 3, title: 'Introduction' },
  SCOPE_OF_WORK: { number: 4, title: 'Scope of Work' },
  EQUIPMENT_AND_PERSONNEL: { number: 5, title: 'Equipment and Personnel' },
  CONTROL_SURVEY: { number: 6, title: 'Control Survey' },
  TOPOGRAPHIC_SURVEY: { number: 7, title: 'Topographic Survey' },
  DATA_PROCESSING: { number: 8, title: 'Data Processing' },
  RESULTS_AND_ACCURACY: { number: 9, title: 'Results and Accuracy' },
  COORDINATE_REGISTER: { number: 10, title: 'Coordinate Register' },
  BENCHMARK_REGISTER: { number: 11, title: 'Benchmark Register' },
  TRAVERSE_COMPUTATIONS: { number: 12, title: 'Traverse Computations' },
  LEVELLING_COMPUTATIONS: { number: 13, title: 'Levelling Computations' },
  CONCLUSIONS_AND_RECOMMENDATIONS: { number: 14, title: 'Conclusions and Recommendations' }
}

function createSection(
  section: ReportSection,
  content: string,
  autoGenerated: boolean
): SectionContent {
  const info = SECTION_TITLES[section]
  const completeness = autoGenerated ? 100 : calculateCompleteness(content)
  return {
    section,
    sectionNumber: info.number,
    title: info.title,
    content,
    autoGenerated,
    completeness
  }
}

function calculateCompleteness(content: string): number {
  const length = content.length
  if (length === 0) return 0
  if (length < 100) return 30
  if (length < 300) return 60
  if (length < 500) return 80
  return 90
}

export function generateTitlePage(input: SurveyReportInput): SectionContent {
  const content = `
    <div class="title-page">
      <h1 style="text-align: center; font-size: 24pt; margin-bottom: 40px;">${input.reportTitle}</h1>
      
      <div style="margin-bottom: 30px;">
        <h2 style="font-size: 14pt; margin-bottom: 10px;">Client</h2>
        <p>${input.clientName}</p>
        <p>${input.clientAddress}</p>
        ${input.contractNumber ? `<p>Contract No: ${input.contractNumber}</p>` : ''}
      </div>
      
      <div style="margin-bottom: 30px;">
        <h2 style="font-size: 14pt; margin-bottom: 10px;">Prepared By</h2>
        <p>${input.firmName}</p>
        <p>${input.firmAddress}</p>
        <p>ISK No: ${input.firmIskNumber}</p>
      </div>
      
      <div style="margin-bottom: 30px;">
        <h2 style="font-size: 14pt; margin-bottom: 10px;">Surveyor</h2>
        <p>${input.surveyorName}</p>
        <p>ISK No: ${input.surveyorIskNumber}</p>
      </div>
      
      <div style="margin-bottom: 30px;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <th style="text-align: left; border: 1px solid #000; padding: 5px;">Rev</th>
            <th style="text-align: left; border: 1px solid #000; padding: 5px;">Date</th>
            <th style="text-align: left; border: 1px solid #000; padding: 5px;">Description</th>
            <th style="text-align: left; border: 1px solid #000; padding: 5px;">By</th>
            <th style="text-align: left; border: 1px solid #000; padding: 5px;">Checked</th>
          </tr>
          <tr>
            <td style="border: 1px solid #000; padding: 5px;">${input.revisionNumber}</td>
            <td style="border: 1px solid #000; padding: 5px;">${input.reportDate}</td>
            <td style="border: 1px solid #000; padding: 5px;">Initial Issue</td>
            <td style="border: 1px solid #000; padding: 5px;">${input.surveyorName}</td>
            <td style="border: 1px solid #000; padding: 5px;"></td>
          </tr>
        </table>
      </div>
      
      <div style="margin-top: 40px; padding: 15px; background: #f5f5f5; border-left: 4px solid #0066cc;">
        <p style="font-style: italic;">
          This report has been prepared in accordance with Kenya Roads Design Manual Part 1 (RDM 1.1) Table 5.4 requirements.
        </p>
      </div>
    </div>
  `
  return createSection('TITLE_PAGE', content, true)
}

export function generateTableOfContents(sections: SectionContent[]): SectionContent {
  let content = '<h2>Table of Contents</h2><ul>'
  sections.forEach((s: any) => {
    content += `<li>${s.sectionNumber}. ${s.title}</li>`
  })
  content += '</ul>'
  return createSection('TABLE_OF_CONTENTS', content, true)
}

export function generateIntroduction(input: SurveyReportInput): SectionContent {
  const completeness = input.projectLocation && input.projectPurpose ? 80 : 30
  const content = `
    <h2>3. Introduction</h2>
    
    <h3>3.1 Background</h3>
    <p>${input.projectPurpose || '[Project purpose to be provided]'}</p>
    
    <h3>3.2 Project Location</h3>
    <p>${input.projectLocation || '[Location to be provided]'}</p>
    <p>County: ${input.county}</p>
    ${input.constituency ? `<p>Constituency: ${input.constituency}</p>` : ''}
    
    <h3>3.3 Survey Period</h3>
    <p>Survey commenced: ${input.surveyPeriodStart}</p>
    <p>Survey completed: ${input.surveyPeriodEnd}</p>
    
    <h3>3.4 Report Structure</h3>
    <p>This report presents the results of the topographic survey carried out in accordance with RDM 1.1 Table 5.4. The report comprises 14 sections covering all aspects of the survey from control establishment through to final results and conclusions.</p>
  `
  return createSection('INTRODUCTION', content, completeness < 100)
}

export function generateScopeOfWork(input: SurveyReportInput): SectionContent {
  let content = '<h2>4. Scope of Work</h2>'
  
  if (input.scopeItems && input.scopeItems.length > 0) {
    content += '<ol>'
    input.scopeItems.forEach((item: any) => {
      content += `<li>${item}</li>`
    })
    content += '</ol>'
  } else {
    content += `
      <ol>
        <li>Establishment of survey control network</li>
        <li>Topographic survey of the project area</li>
        <li>Traverse computation and adjustment</li>
        <li>Levelling and reduced levels</li>
        <li>Survey plan production per Survey Regulations 1994</li>
        <li>Survey report per RDM 1.1 Table 5.4</li>
      </ol>
    `
  }
  
  return createSection('SCOPE_OF_WORK', content, true)
}

export function generateEquipmentAndPersonnel(input: SurveyReportInput): SectionContent {
  let content = `
    <h2>5. Equipment and Personnel</h2>
    
    <h3>5.1 Equipment Used</h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <tr style="background: #eee;">
        <th style="border: 1px solid #000; padding: 5px;">No</th>
        <th style="border: 1px solid #000; padding: 5px;">Equipment</th>
        <th style="border: 1px solid #000; padding: 5px;">Make/Model</th>
        <th style="border: 1px solid #000; padding: 5px;">Serial No</th>
        <th style="border: 1px solid #000; padding: 5px;">Calibration Date</th>
        <th style="border: 1px solid #000; padding: 5px;">Cert No</th>
      </tr>
  `
  
  if (input.equipment && input.equipment.length > 0) {
    input.equipment.forEach((eq, i) => {
      content += `
        <tr>
          <td style="border: 1px solid #000; padding: 5px;">${i + 1}</td>
          <td style="border: 1px solid #000; padding: 5px;">${eq.type}</td>
          <td style="border: 1px solid #000; padding: 5px;">${eq.make}</td>
          <td style="border: 1px solid #000; padding: 5px;">${eq.serialNumber}</td>
          <td style="border: 1px solid #000; padding: 5px;">${eq.calibrationDate}</td>
          <td style="border: 1px solid #000; padding: 5px;">${eq.calibrationCert}</td>
        </tr>
      `
    })
  } else {
    content += '<tr><td colspan="6" style="border: 1px solid #000; padding: 5px;">[Equipment details to be provided]</td></tr>'
  }
  content += '</table>'
  
  content += `
    <h3>5.2 Personnel</h3>
    <table style="width: 100%; border-collapse: collapse;">
      <tr style="background: #eee;">
        <th style="border: 1px solid #000; padding: 5px;">No</th>
        <th style="border: 1px solid #000; padding: 5px;">Name</th>
        <th style="border: 1px solid #000; padding: 5px;">Role</th>
        <th style="border: 1px solid #000; padding: 5px;">Qualifications</th>
      </tr>
  `
  
  if (input.personnel && input.personnel.length > 0) {
    input.personnel.forEach((p, i) => {
      content += `
        <tr>
          <td style="border: 1px solid #000; padding: 5px;">${i + 1}</td>
          <td style="border: 1px solid #000; padding: 5px;">${p.name}</td>
          <td style="border: 1px solid #000; padding: 5px;">${p.role}</td>
          <td style="border: 1px solid #000; padding: 5px;">${p.qualification}</td>
        </tr>
      `
    })
  } else {
    content += '<tr><td colspan="4" style="border: 1px solid #000; padding: 5px;">[Personnel details to be provided]</td></tr>'
  }
  content += '</table>'
  
  return createSection('EQUIPMENT_AND_PERSONNEL', content, (input.equipment?.length ?? 0) > 0)
}

export function generateControlSurvey(input: SurveyReportInput, controlPoints: ControlPoint[]): SectionContent {
  let content = `
    <h2>6. Control Survey</h2>
    
    <h3>6.1 Datum and Projection</h3>
    <p>All coordinates are referenced to ${input.datum} on the ${input.projection} projection.</p>
    <p style="font-style: italic; font-size: 9pt;">Source: Survey Act Cap 299 s.9 — national datum</p>
  `
  
  if (input.gnssMethod) {
    content += `
      <h3>6.2 GNSS Observations</h3>
      <p>${input.gnssMethod}</p>
    `
  }
  
  content += `
    <h3>6.3 Control Point Register</h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <tr style="background: #eee;">
        <th style="border: 1px solid #000; padding: 5px;">Point</th>
        <th style="border: 1px solid #000; padding: 5px;">Order</th>
        <th style="border: 1px solid #000; padding: 5px;">Easting (m)</th>
        <th style="border: 1px solid #000; padding: 5px;">Northing (m)</th>
        <th style="border: 1px solid #000; padding: 5px;">Elevation (m)</th>
        <th style="border: 1px solid #000; padding: 5px;">Mark Type</th>
        <th style="border: 1px solid #000; padding: 5px;">Source</th>
      </tr>
  `
  
  if (controlPoints.length > 0) {
    controlPoints.forEach((cp: any) => {
      content += `
        <tr>
          <td style="border: 1px solid #000; padding: 5px;">${cp.id}</td>
          <td style="border: 1px solid #000; padding: 5px;">${cp.order}</td>
          <td style="border: 1px solid #000; padding: 5px;">${cp.easting.toFixed(4)}</td>
          <td style="border: 1px solid #000; padding: 5px;">${cp.northing.toFixed(4)}</td>
          <td style="border: 1px solid #000; padding: 5px;">${cp.elevation.toFixed(3)}</td>
          <td style="border: 1px solid #000; padding: 5px;">${cp.markType}</td>
          <td style="border: 1px solid #000; padding: 5px;">${cp.source}</td>
        </tr>
      `
    })
  } else {
    content += '<tr><td colspan="7" style="border: 1px solid #000; padding: 5px;">[Control points to be added from survey data]</td></tr>'
  }
  content += '</table>'
  
  content += `
    <h3>6.4 Accuracy Statement</h3>
    <p>Control established to ${getControlAccuracyClass(controlPoints)} accuracy per RDM 1.1 §5.4.</p>
  `
  
  return createSection('CONTROL_SURVEY', content, controlPoints.length > 0)
}

function getControlAccuracyClass(points: ControlPoint[]): string {
  if (points.some((p: any) => p.order === 'PRIMARY')) return 'First Order'
  if (points.some((p: any) => p.order === 'SECONDARY')) return 'Second Order'
  return 'Third Order'
}

export function generateTopographicSurvey(input: SurveyReportInput): SectionContent {
  const methodLabels: Record<string, string> = {
    TOTAL_STATION: 'Total Station',
    GNSS_RTK: 'GNSS RTK',
    LEVEL: 'Digital Level',
    COMBINED: 'Combined Methods'
  }
  
  const content = `
    <h2>7. Topographic Survey</h2>
    
    <h3>7.1 Survey Method</h3>
    <p>${methodLabels[input.surveyMethod] || input.surveyMethod}</p>
    
    <h3>7.2 Instrument</h3>
    <p>${input.instrumentUsed || '[Instrument details to be provided]'}</p>
    
    ${input.pointDensity ? `<h3>7.3 Point Density</h3><p>${input.pointDensity}</p>` : ''}
    ${input.areaHectares ? `<h3>7.4 Coverage</h3><p>${input.areaHectares} hectares</p>` : ''}
  `
  
  return createSection('TOPOGRAPHIC_SURVEY', content, !!input.instrumentUsed)
}

export function generateDataProcessing(input: SurveyReportInput): SectionContent {
  const content = `
    <h2>8. Data Processing</h2>
    
    <p>Data processing was carried out using the following methodology:</p>
    
    <ol>
      <li>Raw data was downloaded from survey instruments to METARDU Survey Computation Platform</li>
      <li>Traverse adjustment was performed using the Bowditch method</li>
      <li>Level reduction was performed using the Rise and Fall method</li>
      <li>Coordinate transformations were applied as required (WGS84/ARC1960/UTM)</li>
      <li>All computations were carried out using METARDU Survey Computation Platform</li>
    </ol>
    
    <p style="font-style: italic; font-size: 9pt;">
      Software: METARDU Survey Computation Platform
    </p>
  `
  
  return createSection('DATA_PROCESSING', content, true)
}

export function generateResultsAndAccuracy(
  input: SurveyReportInput,
  traversePrecision?: number
): SectionContent {
  let content = `
    <h2>9. Results and Accuracy</h2>
  `
  
  content += `
    <h3>9.1 Traverse Accuracy</h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <tr style="background: #eee;">
        <th style="border: 1px solid #000; padding: 5px;">Traverse</th>
        <th style="border: 1px solid #000; padding: 5px;">Precision Ratio</th>
        <th style="border: 1px solid #000; padding: 5px;">Classification</th>
      </tr>
  `
  
  if (traversePrecision) {
    const classification = classifyTraverseAccuracy(traversePrecision)
    content += `
      <tr>
        <td style="border: 1px solid #000; padding: 5px;">Main Traverse</td>
        <td style="border: 1px solid #000; padding: 5px;">1 : ${Math.round(traversePrecision).toLocaleString()}</td>
        <td style="border: 1px solid #000; padding: 5px;">${classification}</td>
      </tr>
    `
  } else if (input.traverseAccuracy) {
    content += `
      <tr>
        <td style="border: 1px solid #000; padding: 5px;">Main Traverse</td>
        <td style="border: 1px solid #000; padding: 5px;">${input.traverseAccuracy}</td>
        <td style="border: 1px solid #000; padding: 5px;">[From field data]</td>
      </tr>
    `
  } else {
    content += '<tr><td colspan="3" style="border: 1px solid #000; padding: 5px;">[Traverse results to be computed]</td></tr>'
  }
  content += '</table>'
  
  content += `
    <h3>9.2 Levelling Accuracy</h3>
    <p>Levelling allowable misclosure: 10√K mm per RDM 1.1 Table 5.1</p>
    ${input.levellingMisclosure ? `<p>Achieved: ${input.levellingMisclosure}</p>` : ''}
  `
  
  return createSection('RESULTS_AND_ACCURACY', content, !!traversePrecision || !!input.traverseAccuracy)
}

function classifyTraverseAccuracy(precision: number): string {
  if (precision >= 10000) return 'First Order Class I — RDM 1.1 Table 5.2'
  if (precision >= 5000) return 'First Order Class II — RDM 1.1 Table 5.2'
  if (precision >= 3000) return 'Second Order Class I — RDM 1.1 Table 5.2'
  if (precision >= 1000) return 'Second Order Class II — RDM 1.1 Table 5.2'
  return 'Third Order — RDM 1.1 Table 5.2 (WARNING: below standard)'
}

export function generateCoordinateRegister(controlPoints: ControlPoint[]): SectionContent {
  let content = `
    <h2>10. Coordinate Register</h2>
    <table style="width: 100%; border-collapse: collapse;">
      <tr style="background: #eee;">
        <th style="border: 1px solid #000; padding: 5px;">No</th>
        <th style="border: 1px solid #000; padding: 5px;">Point ID</th>
        <th style="border: 1px solid #000; padding: 5px;">Easting (m)</th>
        <th style="border: 1px solid #000; padding: 5px;">Northing (m)</th>
        <th style="border: 1px solid #000; padding: 5px;">Elevation (m)</th>
        <th style="border: 1px solid #000; padding: 5px;">Mark Type</th>
        <th style="border: 1px solid #000; padding: 5px;">Remarks</th>
      </tr>
  `
  
  const order: Record<ControlPoint['order'], number> = { PRIMARY: 0, SECONDARY: 1, TERTIARY: 2 }
  const sorted = [...controlPoints].sort((a, b) => order[a.order] - order[b.order])
  
  sorted.forEach((cp, i) => {
    content += `
      <tr>
        <td style="border: 1px solid #000; padding: 5px;">${i + 1}</td>
        <td style="border: 1px solid #000; padding: 5px;">${cp.id}</td>
        <td style="border: 1px solid #000; padding: 5px;">${cp.easting.toFixed(4)}</td>
        <td style="border: 1px solid #000; padding: 5px;">${cp.northing.toFixed(4)}</td>
        <td style="border: 1px solid #000; padding: 5px;">${cp.elevation.toFixed(3)}</td>
        <td style="border: 1px solid #000; padding: 5px;">${cp.markType}</td>
        <td style="border: 1px solid #000; padding: 5px;">${cp.description}</td>
      </tr>
    `
  })
  
  content += '</table>'
  
  return createSection('COORDINATE_REGISTER', content, controlPoints.length > 0)
}

export function generateBenchmarkRegister(benchmarks: ControlPoint[]): SectionContent {
  let content = `
    <h2>11. Benchmark Register</h2>
    <p style="font-style: italic; font-size: 9pt; margin-bottom: 15px;">
      Note: Levels refer to the Kenya National Datum (Mean Sea Level, Mombasa)
    </p>
    
    <table style="width: 100%; border-collapse: collapse;">
      <tr style="background: #eee;">
        <th style="border: 1px solid #000; padding: 5px;">BM No</th>
        <th style="border: 1px solid #000; padding: 5px;">Elevation (m)</th>
        <th style="border: 1px solid #000; padding: 5px;">Description</th>
        <th style="border: 1px solid #000; padding: 5px;">Location</th>
        <th style="border: 1px solid #000; padding: 5px;">Source</th>
      </tr>
  `
  
  if (benchmarks.length > 0) {
    benchmarks.forEach((bm: any) => {
      content += `
        <tr>
          <td style="border: 1px solid #000; padding: 5px;">${bm.id}</td>
          <td style="border: 1px solid #000; padding: 5px;">${bm.elevation.toFixed(3)}</td>
          <td style="border: 1px solid #000; padding: 5px;">${bm.description}</td>
          <td style="border: 1px solid #000; padding: 5px;">${bm.markType}</td>
          <td style="border: 1px solid #000; padding: 5px;">${bm.source}</td>
        </tr>
      `
    })
  } else {
    content += '<tr><td colspan="5" style="border: 1px solid #000; padding: 5px;">[Benchmarks to be added from levelling data]</td></tr>'
  }
  content += '</table>'
  
  return createSection('BENCHMARK_REGISTER', content, benchmarks.length > 0)
}

export function generateTraverseComputations(): SectionContent {
  const content = `
    <h2>12. Traverse Computations</h2>
    
    <p>Traverse computations are performed using the Bowditch method as follows:</p>
    
    <h3>12.1 Raw Observations</h3>
    <p>[Raw traverse data table to be populated from field observations]</p>
    
    <h3>12.2 Computed Bearings and Distances</h3>
    <p>[Bearing and distance computations to be displayed]</p>
    
    <h3>12.3 Latitudes and Departures</h3>
    <p>[Latitude and departure calculations]</p>
    
    <h3>12.4 Closing Errors</h3>
    <p>ΔE = [departure error], ΔN = [latitude error]</p>
    
    <h3>12.5 Bowditch Corrections</h3>
    <p style="font-style: italic;">
      Bowditch correction per leg = -(leg distance / total distance) × closing error
    </p>
    <p>Source: Basak, Surveying and Levelling, Chapter 10</p>
    
    <h3>12.6 Adjusted Coordinates</h3>
    <p>[Adjusted coordinate table]</p>
    
    <h3>12.7 Accuracy Assessment</h3>
    <p>Linear misclosure = √(ΔE² + ΔN²)</p>
    <p>Precision ratio = Perimeter / Linear misclosure</p>
  `
  
  return createSection('TRAVERSE_COMPUTATIONS', content, false)
}

export function generateLevellingComputations(runs?: LevellingRun[]): SectionContent {
  let content = `
    <h2>13. Levelling Computations</h2>
    
    <h3>13.1 Level Run Results</h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <tr style="background: #eee;">
        <th style="border: 1px solid #000; padding: 5px;">Run</th>
        <th style="border: 1px solid #000; padding: 5px;">From BM</th>
        <th style="border: 1px solid #000; padding: 5px;">To BM</th>
        <th style="border: 1px solid #000; padding: 5px;">Distance (km)</th>
        <th style="border: 1px solid #000; padding: 5px;">Misclosure (mm)</th>
        <th style="border: 1px solid #000; padding: 5px;">Allowable (mm)</th>
        <th style="border: 1px solid #000; padding: 5px;">Result</th>
      </tr>
  `
  
  if (runs && runs.length > 0) {
    runs.forEach((run: any) => {
      const resultBadge = run.passes 
        ? '<span style="color: green; font-weight: bold;">PASS</span>'
        : '<span style="color: red; font-weight: bold;">FAIL</span>'
      content += `
        <tr>
          <td style="border: 1px solid #000; padding: 5px;">${run.runId}</td>
          <td style="border: 1px solid #000; padding: 5px;">${run.fromBM}</td>
          <td style="border: 1px solid #000; padding: 5px;">${run.toBM}</td>
          <td style="border: 1px solid #000; padding: 5px;">${run.distance.toFixed(3)}</td>
          <td style="border: 1px solid #000; padding: 5px;">${run.misclosure.toFixed(3)}</td>
          <td style="border: 1px solid #000; padding: 5px;">${run.allowable.toFixed(3)}</td>
          <td style="border: 1px solid #000; padding: 5px;">${resultBadge}</td>
        </tr>
      `
    })
  } else {
    content += '<tr><td colspan="7" style="border: 1px solid #000; padding: 5px;">[Levelling runs to be computed from field data]</td></tr>'
  }
  content += '</table>'
  
  content += `
    <h3>13.2 Arithmetic Check</h3>
    <p>ΣBS - ΣFS = Last RL - First RL</p>
    <p style="font-style: italic;">Source: Basak, Surveying and Levelling, Chapter 5</p>
    
    <h3>13.3 Allowable Misclosure</h3>
    <p>Allowable = 10√K mm per RDM 1.1 Table 5.1 (K = distance in km)</p>
  `
  
  return createSection('LEVELLING_COMPUTATIONS', content, (runs?.length ?? 0) > 0)
}

export function generateConclusions(input: SurveyReportInput): SectionContent {
  let conclusionsContent = ''
  if (input.conclusions && input.conclusions.length > 0) {
    conclusionsContent = '<ol>'
    input.conclusions.forEach((c: any) => {
      conclusionsContent += `<li>${c}</li>`
    })
    conclusionsContent += '</ol>'
  } else {
    conclusionsContent = '<p>[Conclusions to be provided]</p>'
  }
  
  let recommendationsContent = ''
  if (input.recommendations && input.recommendations.length > 0) {
    recommendationsContent = '<ol>'
    input.recommendations.forEach((r: any) => {
      recommendationsContent += `<li>${r}</li>`
    })
    recommendationsContent += '</ol>'
  } else {
    recommendationsContent = '<p>[Recommendations to be provided]</p>'
  }
  
  const content = `
    <h2>14. Conclusions and Recommendations</h2>
    
    <h3>14.1 Conclusions</h3>
    ${conclusionsContent}
    
    <h3>14.2 Recommendations</h3>
    ${recommendationsContent}
    
    <div style="margin-top: 30px; padding: 15px; background: #f5f5f5; border-left: 4px solid #0066cc;">
      <p>
        All survey work was carried out in accordance with the requirements of the
        Kenya Survey Act Cap 299, Survey Regulations 1994, and Kenya Roads Design
        Manual Part 1 (RDM 1.1). The survey data is fit for the intended purpose.
      </p>
    </div>
  `
  
  return createSection('CONCLUSIONS_AND_RECOMMENDATIONS', content, false)
}

export function generateAllSections(
  input: SurveyReportInput,
  controlPoints: ControlPoint[],
  benchmarks: ControlPoint[],
  levellingRuns: LevellingRun[],
  traversePrecision?: number
): SectionContent[] {
  return [
    generateTitlePage(input),
    generateTableOfContents([]),
    generateIntroduction(input),
    generateScopeOfWork(input),
    generateEquipmentAndPersonnel(input),
    generateControlSurvey(input, controlPoints),
    generateTopographicSurvey(input),
    generateDataProcessing(input),
    generateResultsAndAccuracy(input, traversePrecision),
    generateCoordinateRegister(controlPoints),
    generateBenchmarkRegister(benchmarks),
    generateTraverseComputations(),
    generateLevellingComputations(levellingRuns),
    generateConclusions(input)
  ]
}
