import { config } from 'dotenv';
config({ path: '.env' });
config({ path: '.env.local', override: true });

import { generateReportSection } from '../src/lib/ai/nvidiaService';
import * as fs from 'fs';
import * as path from 'path';

async function main() {
  console.log('Generating AI Survey Reports based on Manuals...');
  
  if (!process.env.NVIDIA_API_KEY) {
    console.error('NVIDIA_API_KEY is not set.');
    process.exit(1);
  }

  const reportsToGenerate = [
    {
      surveyType: 'Topographical Survey',
      sectionType: 'Methodology and Control Network',
      projectData: {
        'Client': 'Metardu Engineering',
        'Location': 'Nairobi County Block 12',
        'Area': '2.5 Hectares',
        'Instrument': 'Leica TS16 Total Station & Trimble R12 GNSS',
        'Datums': 'Arc 1960 / UTM Zone 37S'
      },
      instructions: 'Ensure compliance with the RDM 1.1 Topographic Survey Manual. Detail how GNSS base and rover were used to establish the control network, and mention standard deviations.'
    },
    {
      surveyType: 'Cadastral Survey',
      sectionType: 'Boundary Definition and Misclosure Assessment',
      projectData: {
        'Client': 'Ministry of Lands',
        'Location': 'LR No. 4567/8, Kiambu',
        'Surveyors': 'Licensed Surveyor Metardu',
        'Misclosure Error': '0.04m (Linear), Angular (5")',
      },
      instructions: 'Adhere strictly to Cadastral Survey Standards Guidelines Manual and Survey Act. Discuss boundary beacons placed, previous titles analyzed, and declare that the misclosure is within 1:10,000 regulatory limits.'
    },
    {
      surveyType: 'Sectional Property Condominium Survey',
      sectionType: 'Floor Plan and Common Areas Verification',
      projectData: {
        'Building': 'Lochab Site Tower',
        'Units Registered': '45 Apartments, 2 Commercial',
        'Total Floor Area': '4,500 sqm'
      },
      instructions: 'Reference the Sectional Property Act. Declare that all internal dimensions correspond to the building footprint and that common property has been distinctively demarcated from exclusive unit areas.'
    }
  ];

  let artifactMarkdown = '# NVIDIA Gen-AI: Professional Survey Reports\n\nThese documents were generated by the AI referencing the highest compliance standards (RDM, Cadastral Manuals, Sectional Properties Act).\n\n';

  for (const report of reportsToGenerate) {
    console.log(`Generating report section for: ${report.surveyType}...`);
    try {
      const result = await generateReportSection({
        sectionType: report.sectionType,
        surveyType: report.surveyType,
        projectData: report.projectData,
        customInstructions: report.instructions
      });
      artifactMarkdown += `## ${report.surveyType} - ${report.sectionType}\n\n`;
      artifactMarkdown += `> [!NOTE]\n> **Project Data Referenced**: \n> ${JSON.stringify(report.projectData).replace(/[{}]/g, '')}\n\n`;
      artifactMarkdown += `${result}\n\n---\n\n`;
    } catch (err) {
      console.error(`Error generating for ${report.surveyType}:`, err);
      artifactMarkdown += `## ${report.surveyType}\n\n**Error:** ${err}\n\n`;
    }
  }

  const artifactsDir = process.env.APPDATA_DIR ? path.join(process.env.APPDATA_DIR, 'artifacts') : './artifacts';
  if (!fs.existsSync(artifactsDir)) {
    fs.mkdirSync(artifactsDir, { recursive: true });
  }

  const outPath = path.join(artifactsDir, 'ai_survey_documents.md');
  fs.writeFileSync(outPath, artifactMarkdown);
  console.log(`Artifact written to ${outPath}`);
}

main();
