'use client';

import { useState, useEffect, useCallback, useMemo, useRef } from 'react'
import { createClient } from '@/lib/api-client/client'
import { sanitizeHtml } from '@/lib/security/sanitize'
import { usePrint, PrintButton, PrintHeader } from '@/hooks/usePrint'
import { buildSubmissionNumber, normaliseRegistrationNo, validateSubmissionNumber } from '@/lib/submission/format'
import { z } from 'zod'
import { apiPost, ApiError } from '@/lib/api/client'
// import { PHASE13_DEMO_PROJECTS } from '@/lib/standards/rdm11'
import type { 
  SurveyReportInput, 
  SectionContent, 
  ReportSection,
  ReportCompletenessResult,
  EquipmentItem,
  PersonnelItem,
  ControlPoint
} from '@/types/surveyReport'

interface SurveyReportBuilderProps {
  projectId: string
  existingReportId?: string
}

const SECTION_INFO: { section: ReportSection; number: number; title: string; autoGenerated: boolean }[] = [
  { section: 'TITLE_PAGE', number: 1, title: 'Title Page', autoGenerated: false },
  { section: 'TABLE_OF_CONTENTS', number: 2, title: 'Table of Contents', autoGenerated: true },
  { section: 'INTRODUCTION', number: 3, title: 'Introduction', autoGenerated: false },
  { section: 'SCOPE_OF_WORK', number: 4, title: 'Scope of Work', autoGenerated: false },
  { section: 'EQUIPMENT_AND_PERSONNEL', number: 5, title: 'Equipment and Personnel', autoGenerated: false },
  { section: 'CONTROL_SURVEY', number: 6, title: 'Control Survey', autoGenerated: false },
  { section: 'TOPOGRAPHIC_SURVEY', number: 7, title: 'Topographic Survey', autoGenerated: false },
  { section: 'DATA_PROCESSING', number: 8, title: 'Data Processing', autoGenerated: true },
  { section: 'RESULTS_AND_ACCURACY', number: 9, title: 'Results and Accuracy', autoGenerated: false },
  { section: 'COORDINATE_REGISTER', number: 10, title: 'Coordinate Register', autoGenerated: true },
  { section: 'BENCHMARK_REGISTER', number: 11, title: 'Benchmark Register', autoGenerated: true },
  { section: 'TRAVERSE_COMPUTATIONS', number: 12, title: 'Traverse Computations', autoGenerated: true },
  { section: 'LEVELLING_COMPUTATIONS', number: 13, title: 'Levelling Computations', autoGenerated: true },
  { section: 'CONCLUSIONS_AND_RECOMMENDATIONS', number: 14, title: 'Conclusions and Recommendations', autoGenerated: false },
  { section: 'DECLARATION', number: 15, title: 'Surveyor\'s Declaration', autoGenerated: false },
]

const DEFAULT_SCOPE_ITEMS = [
  'Establishment of survey control network',
  'Topographic survey of the project area',
  'Traverse computation and adjustment',
  'Levelling and reduced levels',
  'Survey plan production per Survey Regulations 1994',
  'Survey report per RDM 1.1 Table 5.4'
]

// ─── API response schemas (Zod) ────────────────────────────────────────────
const generateReportResponseSchema = z.object({
  sections: z.array(z.object({}).passthrough()),
  completeness: z.object({}).passthrough(),
  input: z.object({}).passthrough(),
}).passthrough()

const saveReportResponseSchema = z.object({
  id: z.string().optional(),
  saved: z.boolean().optional(),
  created: z.boolean().optional(),
}).passthrough()

export default function SurveyReportBuilder({ projectId, existingReportId }: SurveyReportBuilderProps) {
  const [activeSection, setActiveSection] = useState<ReportSection>('TITLE_PAGE')
  const [reportInput, setReportInput] = useState<Partial<SurveyReportInput>>({})
  const [generatedSections, setGeneratedSections] = useState<SectionContent[]>([])
  const [completeness, setCompleteness] = useState<ReportCompletenessResult | null>(null)
  const [mode, setMode] = useState<'edit' | 'preview'>('edit')
  const [isSaving, setIsSaving] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [isDirty, setIsDirty] = useState(false)
  const [reportId, setReportId] = useState(existingReportId || '')
  const [error, setError] = useState<string | null>(null)
  const [editingAutoSection, setEditingAutoSection] = useState<string | null>(null)
  const [autoSectionDraft, setAutoSectionDraft] = useState('')
  const { print, isPrinting, paperSize, setPaperSize, orientation, setOrientation } = usePrint({ title: 'Survey Report' })

  const dbClient = createClient()

  const generateReport = useCallback(async (input: Partial<SurveyReportInput>) => {
    setIsGenerating(true)
    setError(null)
    try {
      const data = await apiPost(
        '/api/survey-report/generate',
        generateReportResponseSchema,
        { projectId, input }
      )
      setReportInput(data.input as Partial<SurveyReportInput>)
      setGeneratedSections(data.sections as unknown as SectionContent[])
      setCompleteness(data.completeness as unknown as ReportCompletenessResult)
      setIsDirty(false)
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message)
      } else {
        setError(err instanceof Error ? err.message : 'Generation failed')
      }
    } finally {
      setIsGenerating(false)
    }
  }, [projectId])

  const loadReport = useCallback(async () => {
    if (existingReportId) {
      try {
        const { getSurveyReportById } = await import('@/lib/api-client/surveyReports')
        const report = await getSurveyReportById(existingReportId)
        if (report) {
          setReportInput({
            ...report,
            projectId
          } as SurveyReportInput)
          setGeneratedSections(report.sections)
          setReportId(existingReportId)
          // Reconstruct completeness from saved data so auto-save works
          const savedPercent = report.completeness || 0
          setCompleteness({
            overallPercent: savedPercent,
            sectionsComplete: report.sections?.filter((s: any) => s.completeness >= 100).length || 0,
            sectionsIncomplete: report.sections?.filter((s: any) => s.completeness < 100).map((s: any) => ({
              section: s.section,
              sectionNumber: s.sectionNumber,
              missingFields: [],
              completeness: s.completeness,
            })) || [],
            readyToFinalise: savedPercent >= 100,
          })
          return
        }
      } catch (err) {
        console.error('Failed to load report:', err)
      }
    }
    // Only generate fresh report when creating new (no existingReportId)
    await generateReport({ projectId } as SurveyReportInput)
  }, [existingReportId, projectId, generateReport])

  useEffect(() => {
    loadReport()
  }, [loadReport])

  const saveReport = useCallback(async () => {
    if (!completeness) return
    
    setIsSaving(true)
    try {
      const data = await apiPost(
        '/api/survey-report/save',
        saveReportResponseSchema,
        {
          reportId: reportId || undefined,
          projectId,
          input: reportInput,
          sections: generatedSections,
          completeness: completeness.overallPercent
        }
      )
      if (data.id) {
        setReportId(data.id)
      }
      setIsDirty(false)
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message)
      } else {
        setError(err instanceof Error ? err.message : 'Save failed')
      }
    } finally {
      setIsSaving(false)
    }
  }, [completeness, reportId, projectId, reportInput, generatedSections])

  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null)

  useEffect(() => {
    if (isDirty && reportInput.projectId && completeness) {
      if (saveTimeoutRef.current) clearTimeout(saveTimeoutRef.current)
      saveTimeoutRef.current = setTimeout(() => {
        saveReport().catch(() => {})
      }, 2000)
    }
    return () => {
      if (saveTimeoutRef.current) clearTimeout(saveTimeoutRef.current)
    }
  }, [reportInput, generatedSections, isDirty, saveReport, completeness])

  const updateInput = (field: keyof SurveyReportInput, value: any) => {
    setReportInput(prev => ({ ...prev, [field]: value }))
    setIsDirty(true)
  }

  // Demo removed — function no longer needed

  const DEFAULT_DECLARATION = `I, the undersigned, being a Registered Surveyor under the Survey Act (Cap. 299), do hereby declare that:

1. The survey described in this report was carried out under my direct supervision in accordance with the Survey Act (Cap. 299), the Survey Regulations 1994, and the Road Design Manual Part 1 (RDM 1.1, 2025).

2. All field observations, computations, and plans contained herein are accurate and correct to the best of my knowledge and professional belief.

3. The instruments used were in proper adjustment and calibrated within the period specified by the manufacturer and applicable standards.

4. The coordinates, levels, and areas stated in this report have been computed and checked, and are fit for the purpose described in Section 4 (Scope of Work).

Signed: ___________________________    Date: _______________

Name: ___________________________    ISK No: _______________

Firm: ___________________________    Stamp: _______________`

  const exportReport = async (format: 'pdf' | 'docx') => {
    if (!reportId) {
      await saveReport()
    }
    
    try {
      // ponytail: binary download bypasses typed client
      const response = await fetch('/api/survey-report/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reportId: reportId || existingReportId, format })
      })
      
      if (!response.ok) {
        throw new Error('Export failed')
      }
      
      const blob = await response.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${reportInput.reportNumber || 'survey_report'}.${format}`
      a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Export failed')
    }
  }

  const getCompletenessForSection = (section: ReportSection): number => {
    if (!completeness) return 0
    const gap = completeness.sectionsIncomplete.find((g: any) => g.section === section)
    return gap ? gap.completeness : 100
  }

  const isSectionComplete = (section: ReportSection): boolean => {
    return getCompletenessForSection(section) >= 100
  }

  const getSectionBadge = (info: typeof SECTION_INFO[0]) => {
    if (info.autoGenerated) {
      return <span className="text-[10px] px-1.5 py-0.5 bg-gray-200 text-gray-600 rounded">AUTO</span>
    }
    const comp = getCompletenessForSection(info.section)
    if (comp >= 100) {
      return <span className="w-2 h-2 bg-green-500 rounded-full" />
    } else if (comp >= 50) {
      return <span className="w-2 h-2 bg-amber-500 rounded-full" />
    } else {
      return <span className="w-2 h-2 bg-red-500 rounded-full" />
    }
  }

  const renderSectionForm = () => {
    const sectionInfo = SECTION_INFO.find((s: any) => s.section === activeSection)
    if (!sectionInfo) return null

    if (sectionInfo.autoGenerated) {
      const section = generatedSections.find((s: any) => s.section === activeSection)
      const isEditing = editingAutoSection === activeSection

      const startEditing = () => {
        setEditingAutoSection(activeSection)
        // Strip HTML tags for textarea editing
        const raw = section?.content?.replace(/<[^>]*>/g, '\n').replace(/\n{3,}/g, '\n\n').trim() || ''
        setAutoSectionDraft(raw)
      }

      const saveEditing = () => {
        if (!section) return
        const updated = generatedSections.map((s: any) =>
          s.section === activeSection
            ? { ...s, content: autoSectionDraft.split('\n').filter((l: string) => l.trim()).map((l: string) => `<p>${l}</p>`).join('') }
            : s
        )
        setGeneratedSections(updated)
        setEditingAutoSection(null)
        setAutoSectionDraft('')
        setIsDirty(true)
      }

      const cancelEditing = () => {
        setEditingAutoSection(null)
        setAutoSectionDraft('')
      }

      return (
        <div className="space-y-4">
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-sm text-gray-600">
            <p className="flex items-center gap-2">
              <span>(i)</span>
              This section is auto-generated from your project data.
            </p>
          </div>
          {isEditing ? (
            <div className="space-y-3">
              <textarea
                value={autoSectionDraft}
                onChange={e => setAutoSectionDraft(e.target.value)}
                rows={20}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm font-mono"
                placeholder="Edit section content..."
              />
              <div className="flex gap-2">
                <button
                  onClick={saveEditing}
                  className="px-4 py-2 bg-[var(--accent)] text-black rounded-lg text-sm font-medium"
                >
                  Save Changes
                </button>
                <button
                  onClick={cancelEditing}
                  className="px-4 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <div
              className="bg-gray-50 border border-gray-200 rounded-lg p-6 prose prose-sm max-w-none"
              dangerouslySetInnerHTML={{ __html: sanitizeHtml(section?.content || '<p class="text-gray-400">No content generated yet. Click Regenerate to populate this section.</p>') }}
            />
          )}
          <div className="flex gap-2">
            {!isEditing && (
              <button
                onClick={startEditing}
                className="px-4 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm font-medium hover:border-[var(--accent)]"
              >
                Edit Content
              </button>
            )}
            <button
              onClick={() => generateReport(reportInput as SurveyReportInput)}
              disabled={isGenerating}
              className="px-4 py-2 bg-[var(--accent)] text-black rounded-lg text-sm font-medium disabled:opacity-50"
            >
              {isGenerating ? 'Regenerating...' : 'Regenerate'}
            </button>
          </div>
        </div>
      )
    }

    switch (activeSection) {
      case 'TITLE_PAGE':
        return (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1">Report Title</label>
              <input
                type="text"
                value={reportInput.reportTitle || ''}
                onChange={e => updateInput('reportTitle', e.target.value)}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                aria-label="Topographic Survey Report" placeholder="Topographic Survey Report"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Report Number</label>
                <input
                  type="text"
                  value={reportInput.reportNumber || ''}
                  onChange={e => updateInput('reportNumber', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Revision</label>
                <input
                  type="text"
                  value={reportInput.revisionNumber || 'Rev 0'}
                  onChange={e => updateInput('revisionNumber', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Submission Number (SRVY2025-1)</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={reportInput.submissionNumber || ''}
                  onChange={e => updateInput('submissionNumber', e.target.value.toUpperCase())}
                  className={`flex-1 px-3 py-2 bg-[var(--bg-tertiary)] border rounded-lg text-sm font-mono ${
                    reportInput.submissionNumber && !validateSubmissionNumber(reportInput.submissionNumber)
                      ? 'border-red-500'
                      : 'border-[var(--border-color)]'
                  }`}
                  aria-label="RS149_2026_001_R00" placeholder="RS149_2026_001_R00"
                />
                <button
                  onClick={() => {
                    const reg = normaliseRegistrationNo(reportInput.surveyorRegistrationNumber || 'RS149')
                    updateInput('submissionNumber', buildSubmissionNumber({
                      registrationNo: reg,
                      year: new Date().getFullYear(),
                      sequence: 1,
                      revision: 0,
                    }))
                  }}
                  className="px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-xs"
                >
                  Generate
                </button>
              </div>
              <p className="text-xs text-gray-500 mt-1">Format: registration_year_sequence_revision, e.g. RS149_2026_002_R00.</p>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Client Name</label>
                <input
                  type="text"
                  value={reportInput.clientName || ''}
                  onChange={e => updateInput('clientName', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Report Date</label>
                <input
                  type="date"
                  value={reportInput.reportDate || ''}
                  onChange={e => updateInput('reportDate', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Client Address</label>
              <textarea
                value={reportInput.clientAddress || ''}
                onChange={e => updateInput('clientAddress', e.target.value)}
                rows={2}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Firm Name</label>
                <input
                  type="text"
                  value={reportInput.firmName || ''}
                  onChange={e => updateInput('firmName', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">ISK Number</label>
                <input
                  type="text"
                  value={reportInput.firmIskNumber || ''}
                  onChange={e => updateInput('firmIskNumber', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Surveyor Name</label>
                <input
                  type="text"
                  value={reportInput.surveyorName || ''}
                  onChange={e => updateInput('surveyorName', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Surveyor ISK Number</label>
                <input
                  type="text"
                  value={reportInput.surveyorIskNumber || ''}
                  onChange={e => updateInput('surveyorIskNumber', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Surveyor Registration Number</label>
              <input
                type="text"
                value={reportInput.surveyorRegistrationNumber || ''}
                onChange={e => updateInput('surveyorRegistrationNumber', normaliseRegistrationNo(e.target.value))}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm font-mono"
                aria-label="RS149" placeholder="RS149"
              />
            </div>
          </div>
        )

      case 'INTRODUCTION':
        return (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1">Project Location</label>
              <input
                type="text"
                value={reportInput.projectLocation || ''}
                onChange={e => updateInput('projectLocation', e.target.value)}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                aria-label="e.g., Kiserian, Kajiado County" placeholder="e.g., Kiserian, Kajiado County"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">County</label>
                <input
                  type="text"
                  value={reportInput.county || ''}
                  onChange={e => updateInput('county', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Constituency (optional)</label>
                <input
                  type="text"
                  value={reportInput.constituency || ''}
                  onChange={e => updateInput('constituency', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Project Purpose</label>
              <textarea
                value={reportInput.projectPurpose || ''}
                onChange={e => updateInput('projectPurpose', e.target.value)}
                rows={4}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                placeholder="Describe why this survey was commissioned..."
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Site Description</label>
              <textarea
                value={reportInput.siteDescription || ''}
                onChange={e => updateInput('siteDescription', e.target.value)}
                rows={4}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                placeholder="Describe terrain, land use, vegetation, access..."
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Survey Start Date</label>
                <input
                  type="date"
                  value={reportInput.surveyPeriodStart || ''}
                  onChange={e => updateInput('surveyPeriodStart', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Survey End Date</label>
                <input
                  type="date"
                  value={reportInput.surveyPeriodEnd || ''}
                  onChange={e => updateInput('surveyPeriodEnd', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
            </div>
          </div>
        )

      case 'SCOPE_OF_WORK':
        return (
          <div className="space-y-4">
            <label className="block text-sm font-medium mb-1">Scope Items</label>
            {(reportInput.scopeItems || []).map((item, idx) => (
              <div key={idx} className="flex gap-2">
                <input
                  type="text"
                  value={item}
                  onChange={e => {
                    const newItems = [...(reportInput.scopeItems || [])]
                    newItems[idx] = e.target.value
                    updateInput('scopeItems', newItems)
                  }}
                  className="flex-1 px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
                <button
                  onClick={() => {
                    const newItems = (reportInput.scopeItems || []).filter((_, i) => i !== idx)
                    updateInput('scopeItems', newItems)
                  }}
                  className="px-3 py-2 text-red-500 hover:bg-red-50 rounded-lg text-sm"
                >
                  Remove
                </button>
              </div>
            ))}
            <button
              onClick={() => updateInput('scopeItems', [...(reportInput.scopeItems || []), ''])}
              className="px-4 py-2 bg-[var(--accent)] text-black rounded-lg text-sm font-medium"
            >
              + Add Scope Item
            </button>
          </div>
        )

      case 'EQUIPMENT_AND_PERSONNEL':
        return (
          <div className="space-y-6">
            <div>
              <h4 className="text-sm font-medium mb-2">Equipment</h4>
              {(reportInput.equipment || []).map((eq, idx) => (
                <div key={idx} className="grid grid-cols-6 gap-2 mb-2">
                  <input
                    type="text"
                    aria-label="Type" placeholder="Type"
                    value={eq.type}
                    onChange={e => {
                      const newEq = [...(reportInput.equipment || [])]
                      newEq[idx] = { ...newEq[idx], type: e.target.value }
                      updateInput('equipment', newEq)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <input
                    type="text"
                    aria-label="Make" placeholder="Make"
                    value={eq.make}
                    onChange={e => {
                      const newEq = [...(reportInput.equipment || [])]
                      newEq[idx] = { ...newEq[idx], make: e.target.value }
                      updateInput('equipment', newEq)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <input
                    type="text"
                    aria-label="Serial No" placeholder="Serial No"
                    value={eq.serialNumber}
                    onChange={e => {
                      const newEq = [...(reportInput.equipment || [])]
                      newEq[idx] = { ...newEq[idx], serialNumber: e.target.value }
                      updateInput('equipment', newEq)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <input
                    type="date"
                    value={eq.calibrationDate}
                    onChange={e => {
                      const newEq = [...(reportInput.equipment || [])]
                      newEq[idx] = { ...newEq[idx], calibrationDate: e.target.value }
                      updateInput('equipment', newEq)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <input
                    type="text"
                    aria-label="Cert No" placeholder="Cert No"
                    value={eq.calibrationCert}
                    onChange={e => {
                      const newEq = [...(reportInput.equipment || [])]
                      newEq[idx] = { ...newEq[idx], calibrationCert: e.target.value }
                      updateInput('equipment', newEq)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <button
                    onClick={() => {
                      const newEq = (reportInput.equipment || []).filter((_, i) => i !== idx)
                      updateInput('equipment', newEq)
                    }}
                    className="text-red-500 text-xs"
                  >
                    [x]
                  </button>
                </div>
              ))}
              <button
                onClick={() => updateInput('equipment', [...(reportInput.equipment || []), { type: '', make: '', serialNumber: '', calibrationDate: '', calibrationCert: '' }])}
                className="px-3 py-1.5 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded text-xs"
              >
                + Add Equipment
              </button>
            </div>
            <div>
              <h4 className="text-sm font-medium mb-2">Personnel</h4>
              {(reportInput.personnel || []).map((p, idx) => (
                <div key={idx} className="grid grid-cols-4 gap-2 mb-2">
                  <input
                    type="text"
                    aria-label="Name" placeholder="Name"
                    value={p.name}
                    onChange={e => {
                      const newP = [...(reportInput.personnel || [])]
                      newP[idx] = { ...newP[idx], name: e.target.value }
                      updateInput('personnel', newP)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <input
                    type="text"
                    aria-label="Role" placeholder="Role"
                    value={p.role}
                    onChange={e => {
                      const newP = [...(reportInput.personnel || [])]
                      newP[idx] = { ...newP[idx], role: e.target.value }
                      updateInput('personnel', newP)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <input
                    type="text"
                    aria-label="Qualification" placeholder="Qualification"
                    value={p.qualification}
                    onChange={e => {
                      const newP = [...(reportInput.personnel || [])]
                      newP[idx] = { ...newP[idx], qualification: e.target.value }
                      updateInput('personnel', newP)
                    }}
                    className="col-span-1 px-2 py-1.5 bg-[var(--bg-tertiary)] border rounded text-xs"
                  />
                  <button
                    onClick={() => {
                      const newP = (reportInput.personnel || []).filter((_, i) => i !== idx)
                      updateInput('personnel', newP)
                    }}
                    className="text-red-500 text-xs"
                  >
                    [x]
                  </button>
                </div>
              ))}
              <button
                onClick={() => updateInput('personnel', [...(reportInput.personnel || []), { name: '', role: '', qualification: '' }])}
                className="px-3 py-1.5 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded text-xs"
              >
                + Add Personnel
              </button>
            </div>
          </div>
        )

      case 'CONTROL_SURVEY':
        return (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Datum</label>
                <select
                  value={reportInput.datum || 'ARC1960'}
                  onChange={e => updateInput('datum', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                >
                  <option value="ARC1960">ARC1960</option>
                  <option value="WGS84">WGS84</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Projection</label>
                <input
                  type="text"
                  value={reportInput.projection || ''}
                  onChange={e => updateInput('projection', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                  aria-label="e.g., UTM Zone 37S" placeholder="e.g., UTM Zone 37S"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">GNSS Method (optional)</label>
              <input
                type="text"
                value={reportInput.gnssMethod || ''}
                onChange={e => updateInput('gnssMethod', e.target.value)}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                aria-label="e.g., Static GNSS, RTK" placeholder="e.g., Static GNSS, RTK"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Control Points ({reportInput.controlPoints?.length || 0})</label>
              <p className="text-xs text-gray-500 mb-2">Control points are imported from your project survey points.</p>
            </div>
          </div>
        )

      case 'TOPOGRAPHIC_SURVEY':
        return (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Survey Method</label>
                <select
                  value={reportInput.surveyMethod || 'GNSS_RTK'}
                  onChange={e => updateInput('surveyMethod', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                >
                  <option value="TOTAL_STATION">Total Station</option>
                  <option value="GNSS_RTK">GNSS RTK</option>
                  <option value="LEVEL">Level</option>
                  <option value="COMBINED">Combined Methods</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Instrument Used</label>
                <input
                  type="text"
                  value={reportInput.instrumentUsed || ''}
                  onChange={e => updateInput('instrumentUsed', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                  aria-label="e.g., Trimble S7, Leica GS18" placeholder="e.g., Trimble S7, Leica GS18"
                />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Point Density (optional)</label>
                <input
                  type="text"
                  value={reportInput.pointDensity || ''}
                  onChange={e => updateInput('pointDensity', e.target.value)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                  aria-label="e.g., 1 point per 10m²" placeholder="e.g., 1 point per 10m²"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Area (hectares)</label>
                <input
                  type="number"
                  value={reportInput.areaHectares || ''}
                  onChange={e => updateInput('areaHectares', parseFloat(e.target.value) || undefined)}
                  className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                />
              </div>
            </div>
          </div>
        )

      case 'RESULTS_AND_ACCURACY':
        return (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1">Traverse Accuracy</label>
              <input
                type="text"
                value={reportInput.traverseAccuracy || ''}
                onChange={e => updateInput('traverseAccuracy', e.target.value)}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                aria-label="e.g., 1:10,000" placeholder="e.g., 1:10,000"
              />
              <p className="text-xs text-gray-500 mt-1">Auto-populated from traverse computations if available.</p>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Levelling Misclosure</label>
              <input
                type="text"
                value={reportInput.levellingMisclosure || ''}
                onChange={e => updateInput('levellingMisclosure', e.target.value)}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                aria-label="e.g., 12.5 mm" placeholder="e.g., 12.5 mm"
              />
            </div>
          </div>
        )

      case 'CONCLUSIONS_AND_RECOMMENDATIONS':
        return (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">Conclusions</label>
              {(reportInput.conclusions || []).map((c, idx) => (
                <div key={idx} className="flex gap-2 mb-2">
                  <textarea
                    value={c}
                    onChange={e => {
                      const newC = [...(reportInput.conclusions || [])]
                      newC[idx] = e.target.value
                      updateInput('conclusions', newC)
                    }}
                    rows={2}
                    className="flex-1 px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                  />
                  <button
                    onClick={() => updateInput('conclusions', (reportInput.conclusions || []).filter((_, i) => i !== idx))}
                    className="px-2 text-red-500 hover:bg-red-50 rounded"
                  >
                    [x]
                  </button>
                </div>
              ))}
              <button
                onClick={() => updateInput('conclusions', [...(reportInput.conclusions || []), ''])}
                className="px-3 py-1.5 bg-[var(--accent)] text-black rounded text-xs font-medium"
              >
                + Add Conclusion
              </button>
            </div>
            <div>
              <label className="block text-sm font-medium mb-2">Recommendations</label>
              {(reportInput.recommendations || []).map((r, idx) => (
                <div key={idx} className="flex gap-2 mb-2">
                  <textarea
                    value={r}
                    onChange={e => {
                      const newR = [...(reportInput.recommendations || [])]
                      newR[idx] = e.target.value
                      updateInput('recommendations', newR)
                    }}
                    rows={2}
                    className="flex-1 px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm"
                  />
                  <button
                    onClick={() => updateInput('recommendations', (reportInput.recommendations || []).filter((_, i) => i !== idx))}
                    className="px-2 text-red-500 hover:bg-red-50 rounded"
                  >
                    [x]
                  </button>
                </div>
              ))}
              <button
                onClick={() => updateInput('recommendations', [...(reportInput.recommendations || []), ''])}
                className="px-3 py-1.5 bg-[var(--accent)] text-black rounded text-xs font-medium"
              >
                + Add Recommendation
              </button>
            </div>
          </div>
        )

      case 'DECLARATION':
        return (
          <div className="space-y-4">
            <div className="p-3 border border-amber-700/40 bg-amber-950/20 rounded-lg text-xs text-amber-200 leading-6">
              <strong>Survey Regulations 1994, Reg. 3(2)</strong> — Every survey report submitted to the Director of Surveys
              must contain a signed declaration by the licensed surveyor who supervised the work.
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Declaration Statement</label>
              <textarea
                value={reportInput.declarationStatement || ''}
                onChange={e => updateInput('declarationStatement', e.target.value)}
                rows={14}
                className="w-full px-3 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-sm font-mono leading-6"
                placeholder="I, the undersigned, being a Registered Surveyor under the Survey Act (Cap. 299)..."
              />
            </div>
            <button
              onClick={() => updateInput('declarationStatement', DEFAULT_DECLARATION)}
              className="px-4 py-2 bg-[var(--bg-tertiary)] border border-[var(--border-color)] rounded-lg text-xs font-medium hover:border-[var(--accent)]"
            >
              Load Standard Declaration Template
            </button>
          </div>
        )

      default:
        return <p className="text-gray-500">No editing available for this section.</p>
    }
  }

  const renderPreview = () => {
    return (
      <div className="bg-white text-black p-8 max-w-[794px] mx-auto shadow-lg min-h-[1123px]">
        {generatedSections.map((section: any) => (
          <div key={section.section} className={section.sectionNumber > 1 ? 'mt-8' : ''}>
            {section.sectionNumber === 1 ? (
              <div dangerouslySetInnerHTML={{ __html: sanitizeHtml(section.content) }} />
            ) : (
              <>
                <h2 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4">
                  {section.sectionNumber}. {section.title}
                </h2>
                <div dangerouslySetInnerHTML={{ __html: sanitizeHtml(section.content) }} />
              </>
            )}
          </div>
        ))}
      </div>
    )
  }

  if (isGenerating && !generatedSections.length) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="w-8 h-8 border-2 border-[var(--accent)] border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-[var(--text-muted)]">Generating report...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="flex h-screen overflow-hidden">
      {/* Left Sidebar */}
      <div className="w-72 border-r border-[var(--border-color)] bg-[var(--bg-card)] flex flex-col overflow-hidden">
        <div className="p-4 border-b border-[var(--border-color)]">
          <h1 className="text-lg font-semibold">Survey Report</h1>
          <div className="flex gap-1 mt-3 bg-[var(--bg-tertiary)] p-1 rounded-lg">
            <button
              onClick={() => setMode('edit')}
              className={`flex-1 py-1.5 text-xs font-medium rounded ${mode === 'edit' ? 'bg-[var(--accent)] text-black' : 'text-[var(--text-muted)]'}`}
            >
              Edit
            </button>
            <button
              onClick={() => setMode('preview')}
              className={`flex-1 py-1.5 text-xs font-medium rounded ${mode === 'preview' ? 'bg-[var(--accent)] text-black' : 'text-[var(--text-muted)]'}`}
            >
              Preview
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-2">
          {SECTION_INFO.map((info: any) => (
            <button
              key={info.section}
              onClick={() => setActiveSection(info.section)}
              className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm mb-1 ${
                activeSection === info.section 
                  ? 'bg-blue-50 text-blue-700 border border-blue-200' 
                  : 'hover:bg-[var(--bg-tertiary)]'
              }`}
            >
              <span className="flex items-center gap-2">
                <span className="text-xs text-[var(--text-muted)]">{info.number}.</span>
                <span className="truncate">{info.title}</span>
              </span>
              {getSectionBadge(info)}
            </button>
          ))}
        </div>

        <div className="p-4 border-t border-[var(--border-color)]">
          <div className="text-xs text-[var(--text-muted)] mb-2">
            Report Completeness
          </div>
          <div className="w-full h-2 bg-[var(--bg-tertiary)] rounded-full overflow-hidden">
            <div 
              className="h-full bg-green-500 transition-all"
              style={{ width: `${completeness?.overallPercent || 0}%` }}
            />
          </div>
          <div className="flex justify-between text-xs mt-1">
            <span className="text-[var(--text-muted)]">{completeness?.overallPercent || 0}% complete</span>
            <span className="text-[var(--text-muted)]">{completeness?.sectionsComplete || 0} of 15 sections</span>
          </div>
        </div>

        <div className="p-4 border-t border-[var(--border-color)] space-y-2">
          <button
            onClick={saveReport}
            disabled={isSaving}
            className="w-full px-4 py-2 bg-[var(--bg-tertiary)] hover:bg-[var(--border-hover)] border border-[var(--border-color)] rounded-lg text-sm font-medium disabled:opacity-50"
          >
            {isSaving ? 'Saving...' : 'Save Draft'}
          </button>
          <button
            onClick={saveReport}
            disabled={!completeness?.readyToFinalise || isSaving}
            className="w-full px-4 py-2 bg-[var(--accent)] hover:bg-[var(--accent-dim)] text-black rounded-lg text-sm font-medium disabled:opacity-40 disabled:cursor-not-allowed"
            title={!completeness?.readyToFinalise ? 'Complete all required sections to finalise' : ''}
          >
            Finalise Report
          </button>
        </div>
      </div>

      {/* Right Panel */}
      <div className="flex-1 overflow-y-auto p-8 bg-[var(--bg-primary)]">
        {error && (
          <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
            {error}
          </div>
        )}

        {mode === 'edit' ? (
          <div className="max-w-2xl mx-auto">
            <div className="mb-6">
              <h2 className="text-xl font-semibold">
                Section {SECTION_INFO.find((s: any) => s.section === activeSection)?.number} — {SECTION_INFO.find((s: any) => s.section === activeSection)?.title}
              </h2>
            </div>
            {renderSectionForm()}
          </div>
        ) : (
          <div>
            <div className="sticky top-0 bg-[var(--bg-primary)] py-4 border-b border-[var(--border-color)] mb-6 flex gap-2 no-print print-hide">
              <PrintButton
                print={print}
                isPrinting={isPrinting}
                paperSize={paperSize}
                setPaperSize={setPaperSize}
                orientation={orientation}
                setOrientation={setOrientation}
                printTitle="Survey Report"
              />
              <button
                onClick={() => exportReport('pdf')}
                className="px-4 py-2 bg-[var(--accent)] text-black rounded-lg text-sm font-medium"
              >
                Download PDF
              </button>
              <button
                onClick={() => exportReport('docx')}
                className="px-4 py-2 bg-[var(--accent)] text-black rounded-lg text-sm font-medium"
              >
                Download Word
              </button>
            </div>
            <PrintHeader title="Survey Report" />
            {renderPreview()}
          </div>
        )}
      </div>
    </div>
  )
}
