/**
 * Tier 1 Regression Tests — Optimistic Locking + Audit Helpers
 *
 * CONTEXT
 * -------
 * T1.8: Added db.updateWithOptimisticLock() / db.deleteWithOptimisticLock()
 *       to eliminate the TOCTOU race in the old checkOptimisticLock() helper.
 * T1.9: Fixed createAuditLog() and logAuditEvent() which referenced
 *       non-existent columns and silently swallowed the Postgres error.
 *
 * These tests verify the CONTRACT without requiring a live database:
 * - The SQL generated by the helpers includes the optimistic-lock guard
 *   in the WHERE clause (not just in a pre-check).
 * - The assertTable whitelist rejects unknown table names.
 * - The audit helpers use the correct column names.
 */

import { db } from '@/lib/db'

// ════════════════════════════════════════════════════════════════════════════
// T1.8 — db.updateWithOptimisticLock contract
// ════════════════════════════════════════════════════════════════════════════
describe('[T1.8] db.updateWithOptimisticLock — SQL guard contract', () => {
  // We spy on db.query to capture the SQL without hitting a real DB.
  let querySpy: jest.SpyInstance

  beforeEach(() => {
    querySpy = jest.spyOn(db, 'query').mockResolvedValue({ rows: [{ id: 'test-id' }], rowCount: 1 } as never)
  })

  afterEach(() => {
    querySpy.mockRestore()
  })

  it('includes "AND updated_at = $N" in the WHERE clause (not just a pre-check)', async () => {
    await db.updateWithOptimisticLock(
      'projects',
      '123e4567-e89b-12d3-a456-426614174000',
      { name: 'Updated Project' },
      '2026-07-09T00:00:00Z',
    )

    const sql = querySpy.mock.calls[0][0] as string
    // The guard MUST be in the UPDATE's WHERE clause — this is the whole
    // point of T1.8. The old checkOptimisticLock did a separate SELECT.
    expect(sql).toMatch(/WHERE id = \$\d+ AND updated_at = \$\d+/)
    expect(sql).toContain('UPDATE projects')
    expect(sql).toContain('SET name = $1')
    expect(sql).toContain('updated_at = NOW()')
    expect(sql).toContain('RETURNING *')
  })

  it('parameterizes values (no SQL injection via column values)', async () => {
    const malicious = "'; DROP TABLE projects; --"
    await db.updateWithOptimisticLock(
      'projects',
      '123e4567-e89b-12d3-a456-426614174000',
      { name: malicious },
      '2026-07-09T00:00:00Z',
    )

    const params = querySpy.mock.calls[0][1] as unknown[]
    // The malicious string must be a parameter, not interpolated into SQL.
    expect(params).toContain(malicious)
    const sql = querySpy.mock.calls[0][0] as string
    expect(sql).not.toContain('DROP TABLE')
  })

  it('rejects table names not in the whitelist (SQL injection guard)', async () => {
    await expect(
      db.updateWithOptimisticLock(
        'users; DROP TABLE projects; --',
        '123e4567-e89b-12d3-a456-426614174000',
        { name: 'x' },
        '2026-07-09T00:00:00Z',
      )
    ).rejects.toThrow(/not in the optimistic-lock whitelist/)
  })

  it('rejects empty updates object', async () => {
    await expect(
      db.updateWithOptimisticLock(
        'projects',
        '123e4567-e89b-12d3-a456-426614174000',
        {},
        '2026-07-09T00:00:00Z',
      )
    ).rejects.toThrow(/no columns to update/)
  })

  it('returns null when 0 rows affected (conflict)', async () => {
    querySpy.mockRestore()
    querySpy = jest.spyOn(db, 'query').mockResolvedValue({ rows: [], rowCount: 0 } as never)

    const result = await db.updateWithOptimisticLock(
      'projects',
      '123e4567-e89b-12d3-a456-426614174000',
      { name: 'Updated' },
      '2026-07-09T00:00:00Z',
    )

    expect(result).toBeNull()
  })
})

// ════════════════════════════════════════════════════════════════════════════
// T1.8 — db.deleteWithOptimisticLock contract
// ════════════════════════════════════════════════════════════════════════════
describe('[T1.8] db.deleteWithOptimisticLock — SQL guard contract', () => {
  let querySpy: jest.SpyInstance

  beforeEach(() => {
    querySpy = jest.spyOn(db, 'query').mockResolvedValue({ rows: [], rowCount: 1 } as never)
  })

  afterEach(() => {
    querySpy.mockRestore()
  })

  it('includes "AND updated_at = $2" in the DELETE WHERE clause', async () => {
    await db.deleteWithOptimisticLock(
      'projects',
      '123e4567-e89b-12d3-a456-426614174000',
      '2026-07-09T00:00:00Z',
    )

    const sql = querySpy.mock.calls[0][0] as string
    expect(sql).toMatch(/DELETE FROM projects\s+WHERE id = \$1 AND updated_at = \$2/)
  })

  it('returns true when a row was deleted', async () => {
    querySpy.mockRestore()
    querySpy = jest.spyOn(db, 'query').mockResolvedValue({ rows: [], rowCount: 1 } as never)

    const result = await db.deleteWithOptimisticLock(
      'projects',
      '123e4567-e89b-12d3-a456-426614174000',
      '2026-07-09T00:00:00Z',
    )
    expect(result).toBe(true)
  })

  it('returns false when 0 rows deleted (conflict)', async () => {
    querySpy.mockRestore()
    querySpy = jest.spyOn(db, 'query').mockResolvedValue({ rows: [], rowCount: 0 } as never)

    const result = await db.deleteWithOptimisticLock(
      'projects',
      '123e4567-e89b-12d3-a456-426614174000',
      '2026-07-09T00:00:00Z',
    )
    expect(result).toBe(false)
  })

  it('rejects unknown table names', async () => {
    await expect(
      db.deleteWithOptimisticLock(
        'evil_table',
        '123e4567-e89b-12d3-a456-426614174000',
        '2026-07-09T00:00:00Z',
      )
    ).rejects.toThrow(/not in the optimistic-lock whitelist/)
  })
})

// ════════════════════════════════════════════════════════════════════════════
// T1.9 — createAuditLog uses correct column names
// ════════════════════════════════════════════════════════════════════════════
describe('[T1.9] createAuditLog — correct column names (no silent failure)', () => {
  let querySpy: jest.SpyInstance

  beforeEach(() => {
    querySpy = jest.spyOn(db, 'query').mockResolvedValue({
      rows: [{ id: 'audit-1', action: 'UPDATE' }],
      rowCount: 1,
    } as never)
  })

  afterEach(() => {
    querySpy.mockRestore()
  })

  it('INSERTs into table_name + record_id (NOT entity_type + entity_id)', async () => {
    const { createAuditLog } = await import('@/lib/db/queries/audit')
    await createAuditLog({
      entityType: 'projects',
      entityId: '123e4567-e89b-12d3-a456-426614174000',
      action: 'UPDATE',
      userId: '123e4567-e89b-12d3-a456-426614174001',
      userName: 'test@example.com',
    })

    const sql = querySpy.mock.calls[0][0] as string
    // T1.9: MUST use the real column names. The old code used entity_type /
    // entity_id which don't exist in the schema.
    expect(sql).toContain('table_name')
    expect(sql).toContain('record_id')
    expect(sql).not.toContain('entity_type')
    expect(sql).not.toContain('entity_id')
    expect(sql).not.toContain('user_name')
    expect(sql).toContain('details') // changes → details
  })

  it('stores userName inside the details JSONB (no dedicated column)', async () => {
    const { createAuditLog } = await import('@/lib/db/queries/audit')
    await createAuditLog({
      entityType: 'projects',
      entityId: '123e4567-e89b-12d3-a456-426614174000',
      action: 'UPDATE',
      userId: '123e4567-e89b-12d3-a456-426614174001',
      userName: 'test@example.com',
      changes: '{"field": "value"}',
    })

    const params = querySpy.mock.calls[0][1] as unknown[]
    // The 5th param is the details JSONB. It must contain user_name.
    const details = JSON.parse(params[4] as string)
    expect(details.user_name).toBe('test@example.com')
    expect(details.changes).toEqual({ field: 'value' })
  })

  it('returns null on DB error (fire-and-forget) but logs with context', async () => {
    querySpy.mockRestore()
    querySpy = jest.spyOn(db, 'query').mockRejectedValue(new Error('column does not exist'))
    const errorSpy = jest.spyOn(console, 'error').mockImplementation(() => {})

    const { createAuditLog } = await import('@/lib/db/queries/audit')
    const result = await createAuditLog({
      entityType: 'projects',
      entityId: '123e4567-e89b-12d3-a456-426614174000',
      action: 'UPDATE',
      userId: '123e4567-e89b-12d3-a456-426614174001',
      userName: 'test@example.com',
    })

    expect(result).toBeNull()
    // T1.9: The error MUST be logged with context (not silently swallowed).
    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining('[audit] createAuditLog FAILED'),
      expect.objectContaining({
        entityType: 'projects',
        action: 'UPDATE',
      })
    )

    errorSpy.mockRestore()
  })
})

// ════════════════════════════════════════════════════════════════════════════
// T1.9 — logAuditEvent uses correct column names
// ════════════════════════════════════════════════════════════════════════════
describe('[T1.9] logAuditEvent — correct column names (no silent failure)', () => {
  let querySpy: jest.SpyInstance

  beforeEach(() => {
    querySpy = jest.spyOn(db, 'query').mockResolvedValue({
      rows: [{ id: 'audit-uuid-1' }],
      rowCount: 1,
    } as never)
  })

  afterEach(() => {
    querySpy.mockRestore()
  })

  it('INSERTs into table_name + record_id (NOT resource_type + resource_id)', async () => {
    const { logAuditEvent } = await import('@/lib/enterprise/auditTrail')
    await logAuditEvent({
      userId: '123e4567-e89b-12d3-a456-426614174001',
      action: 'USER_SUSPENDED',
      resourceType: 'users',
      resourceId: '123e4567-e89b-12d3-a456-426614174000',
      timestamp: new Date('2026-07-09T00:00:00Z'),
    })

    const sql = querySpy.mock.calls[0][0] as string
    // T1.9: MUST use real column names.
    expect(sql).toContain('table_name')
    expect(sql).toContain('record_id')
    expect(sql).not.toContain('resource_type')
    expect(sql).not.toContain('resource_id')
    expect(sql).not.toContain('user_agent') // no such column
  })

  it('stores userAgent inside the details JSONB', async () => {
    const { logAuditEvent } = await import('@/lib/enterprise/auditTrail')
    await logAuditEvent({
      userId: '123e4567-e89b-12d3-a456-426614174001',
      action: 'LOGIN',
      resourceType: 'auth',
      userAgent: 'Mozilla/5.0',
      timestamp: new Date(),
    })

    const params = querySpy.mock.calls[0][1] as unknown[]
    const details = JSON.parse(params[4] as string)
    expect(details.user_agent).toBe('Mozilla/5.0')
  })

  it('returns a UUID string (not a number — schema uses uuid_generate_v4)', async () => {
    const { logAuditEvent } = await import('@/lib/enterprise/auditTrail')
    const id = await logAuditEvent({
      userId: '123e4567-e89b-12d3-a456-426614174001',
      action: 'TEST',
      resourceType: 'test',
      timestamp: new Date(),
    })

    expect(typeof id).toBe('string')
    // The old code returned `number` (SERIAL) — the real schema uses UUID.
    expect(id).not.toBeNaN()
  })
})
